Rework Navigation
nextcloud/forms pull request #1168
Opened 2022-04-13 18:15 UTC by Chartman123

Closes #422 and #423

Signed-off-by: Christian Hartmann <chris-hartmann@gmx.de>

2022-04-16 14:23 UTC, jotoeri commented
So - after quite a bunch of more css-shit, i think i got a solution, that i'd be fine with. How do you think, @Chartman123 ? 😉 
![grafik](https://user-images.githubusercontent.com/47433654/163678662-8737d2e6-2437-4342-8a5e-489c4b30c32a.png)

2022-04-16 17:05 UTC, Chartman123 commented
Looking good :) I will check it out later.

2022-04-21 11:16 UTC, jancborchardt commented
Looking very nice! :) Just for clarification, does the number counter show the responses since last viewing, or the total response count?

2022-04-21 11:27 UTC, Chartman123 commented
> does the number counter show the responses since last viewing, or the total response count?

At the moment only the total. If we want to show a highlighted counter for new responses since the last visit, we would need to store the last visit timestamp and compare it to the submissions for the form.

2022-04-21 11:30 UTC, skjnldsv commented on src/components/AppNavigationForm.vue
> +.list-item-form {
I don't think that is needed, you should not need custom css as the [`ListItem`](https://nextcloud-vue-components.netlify.app/#/Components/List%20items?id=listitem) should already cover the proper design

2022-04-21 12:54 UTC, jancborchardt commented
Thanks @Chartman123, total count is fine, no need to overcomplicate it since we have notifications for new responses. :)

2022-04-21 20:21 UTC, jotoeri commented on src/components/AppNavigationForm.vue
> +.list-item-form {
That was basically me, introducing that... 🙃 
It implements two points:
- The Listitem as is, is really large, which is especially compared to the old AppNavigationItem a massive increase of used space, which is IMO not necessary. Especially if the form list becomes long, this will be quite annoying to use. Thus the CSS decreases its height a bit. Also the mix of items with/without second line needs a little more compact design to blend in properly.
- The ListItem is not made to be used without second line but with Counter. Thus the second part of the CSS brings this in a usable view. Would of course be better to solve that in the lib on long term, but that might be breaking changes there, so I'd for now solve our problem here.

The picture in my comment above basically shows the total result including all necessary variants, that we might show.
I can give you more details and images when I'm back home next week... (Or @Chartman123 can of course, too 😉 )

2022-04-24 21:04 UTC, jotoeri commented on src/components/AppNavigationForm.vue
> +.list-item-form {
Old way with AppNavigationItem:
![grafik](https://user-images.githubusercontent.com/47433654/164996372-90e0bbc1-6bba-4b72-866a-c5752d4ee076.png)

ListItem with CSS as in this PR:
![Animation](https://user-images.githubusercontent.com/47433654/164996447-13cd7314-c73f-4555-a0b4-17feb13b7fdd.gif)


ListItem without CSS, same content:
![Animation](https://user-images.githubusercontent.com/47433654/164996305-9cd5c448-f1bd-45de-8328-f6dd66b8ab91.gif)

2022-04-25 17:47 UTC, jotoeri approved these changes
Small code-beauty would be good, but apart from that i'm happy with the current state! 🎉

2022-04-25 17:47 UTC, jotoeri commented on src/components/AppNavigationForm.vue
> +			return false
A bit shorter & cleaner, if you directly return the result:
```suggestion
			return this.form.hash === this.$route.params.hash
```

2022-04-25 17:47 UTC, jotoeri commented on src/components/AppNavigationForm.vue
> +				return t('forms', 'Expires {relativeDate}', { relativeDate: expireDate })
Also a small code-beauty: With according naming, you can directly pass the variable without separately assigning.
```suggestion
				const relativeDate = moment(this.form.expires, 'X').fromNow()
				if (this.isExpired) {
					return t('forms', 'Expired {relativeDate}', { relativeDate })
				}
				return t('forms', 'Expires {relativeDate}', { relativeDate })
```

2022-04-25 21:27 UTC, jancborchardt commented on src/components/AppNavigationForm.vue
> +.list-item-form {
Sounds like something that should be fixed in the Vue components instead though?

That is, the height should ideally stay the same, but it's nice that entries without a subline have their title and counter vertically centered.

@skjnldsv @marcoambrosini

2022-04-26 08:16 UTC, skjnldsv commented on src/components/AppNavigationForm.vue
> +.list-item-form {
> Sounds like something that should be fixed in the Vue components instead though?

Exactly what i was gnna say! :wink:

2022-04-26 08:16 UTC, skjnldsv requested changes
Please fix the component instead

2022-07-10 12:34 UTC, jotoeri commented
Did a rebase here, maybe i'll find some time to look into the library. 😉

2022-07-21 18:12 UTC, Chartman123 commented
> * [x]  To fix on public link if not logged in

Fixed by checking for $this->currentUser in the if statements

2022-07-21 19:39 UTC, jotoeri commented
I wont get to work on it on the weekend. Hopefully end of next week then.

2022-07-29 08:48 UTC, jotoeri commented
With https://github.com/nextcloud/nextcloud-vue/pull/2856 now looks like:
![new](https://user-images.githubusercontent.com/47433654/181721275-50194964-aa33-49da-85bf-ad16a89ad0e8.png)

2022-07-29 08:50 UTC, jotoeri commented on src/components/AppNavigationForm.vue
> +.list-item-form {
Done. :muscle:

2022-08-04 16:51 UTC, Chartman123 commented
@jancborchardt @skjnldsv The Vue component has been made ready for this now. Could you please check again if we should adjust something here or if we can merge it? Thanks 🙃

2022-08-11 11:37 UTC, jotoeri approved these changes
Still fine by me... 👍 🙃

2022-08-11 17:00 UTC, merged