Restrict Form Creation
nextcloud/forms pull request #1199
Opened 2022-05-08 12:00 UTC by jotoeri

Signed-off-by: Jonas Rittershofer <jotoeri@users.noreply.github.com>

2022-05-08 13:11 UTC, jotoeri commented on src/Forms.vue
> -		noForms() {
Just as explanation:
As long as it is not evaluated, it renders as if beeing false. Thus, i inverted its meaning to avoid a glitch on the AppNavigation while loading.

2022-05-09 22:16 UTC, jotoeri commented
Waiting for
- [ ] #1087 
- [ ] #1126

2022-06-05 13:11 UTC, Chartman123 approved these changes
Didn't find any problems running this code in my local instance :)

2022-06-16 14:33 UTC, jancborchardt requested changes
Good stuff! :) Just some wording feedback

2022-06-16 14:33 UTC, jancborchardt commented on src/FormsSettings.vue
> +		<SettingsSection :title="t('forms', 'Form Creation')"
```suggestion
		<SettingsSection :title="t('forms', 'Form creation')"
```

We use sentence case as per design guidelines, not Capital Case. :)

2022-06-16 14:33 UTC, jancborchardt commented on src/FormsSettings.vue
> +			:description="t('forms', 'Decide who can create forms.')">
This subline doesn’t really add anything here, so we can also remove it.

2022-06-16 14:33 UTC, jancborchardt commented on src/FormsSettings.vue
> +		<SettingsSection :title="t('forms', 'Form Sharing')"
```suggestion
		<SettingsSection :title="t('forms', 'Form sharing')"
```

Sentence case

2022-06-16 14:33 UTC, jancborchardt commented on src/FormsSettings.vue
> +			:description="t('forms', 'Configure which options are available for sharing a form.')">
Subline doesn’t add anything here either, can be cut.

2022-06-16 14:33 UTC, jancborchardt commented on src/FormsSettings.vue
> +				{{ t('forms', 'Allow sharing by Public link') }}
```suggestion
				{{ t('forms', 'Allow sharing by link') }}
```

A link is not "public" (which can be understood as being published somewhere), it’s just a link. :) In the app itself we also just say "Share link".

2022-06-16 14:33 UTC, jancborchardt commented on src/FormsSettings.vue
> +				{{ t('forms', 'Allow sharing to all logged in users') }}
```suggestion
				{{ t('forms', 'Allow sharing to all logged in accounts') }}
```

This is to remove the term "user" from the interface language and to also ensure gender neutrality in other languages. (See https://help.nextcloud.com/t/geschlechtsneutrale-sprache-genderneutral/82200/107 (German))

2022-06-26 22:15 UTC, jotoeri commented
> Good stuff! :) Just some wording feedback

Everything fixed. 🙂

2022-06-27 11:30 UTC, Chartman123 reviewed
Two more "users" in the texts. Adjust right now or create a PR to change all occurrences at once?

2022-06-27 11:30 UTC, Chartman123 commented on src/components/SidebarTabs/SharingSidebarTab.vue
> +					{{ t('forms', 'Permit access to all logged in users') }}
Should we change this to 'accounts', too?

2022-06-27 11:30 UTC, Chartman123 commented on src/components/SidebarTabs/SharingSidebarTab.vue
> +					{{ t('forms', 'Show to all users on sidebar') }}
Same here

2022-06-27 19:55 UTC, jotoeri commented on src/components/SidebarTabs/SharingSidebarTab.vue
> +					{{ t('forms', 'Permit access to all logged in users') }}
Well yeah, included a few more... 👍 🤷‍♂️

2022-07-01 15:49 UTC, merged

2022-08-08 09:43 UTC, Tom5421 commented
Is this available in the Forms app yet, I have the app but I can't see this screen in the settings page

2023-02-11 19:28 UTC, greavette commented
Hello @jotoeri , Appreciate the reply!  I'm using Forms version 3.04 on Nextcloud  version 25.03

I've tried testing this but could not get this to work. Please assist with what I'm doing incorrectly.

Mary has a limited account on our NextCloud (Not Admin).  She does not have access to Forms.
I'm the Admin and I created a Form for Mary to complete.  I shared this form with Mary.

When I log in to Mary's Nextcloud I don't see the form I shared with her.  

Am I misunderstanding how this works? My expectation was that I could create a form for Mary to complete, Mary would see the form and complete it and send it back to me for review.  Once Mary has completed the form I will unshare and keep the results for historical purposes.  

What am I missing?  Thank you.

2023-02-13 11:11 UTC, jotoeri commented
Hey @greavette
generally it sounds like your understanding of the feature is right. I currently cant fully track, what you did, but maybe you disabled the app by the app-management?
For this feature to work, you must enable the app for all users within your nextcloud and then you find within the admin-settings a section for forms and the point to restrict form-creation to groups.

If that does not help, please head over to the forum https://help.nextcloud.com for further support, since we cant provide support here on github.

Greets,
Jonas