Invert submitOnce
nextcloud/forms pull request #1252
Opened 2022-07-10 19:07 UTC by jotoeri

Fixing #1193

2022-07-10 19:34 UTC, Chartman123 requested changes

2022-07-10 19:34 UTC, Chartman123 commented on docs/DataStructure.md
> +| submitMultiple  | Boolean         |              | If users are only allowed to submit multiple times to the form |
Word 'only' should be removed with multiple submissions

2022-07-10 19:59 UTC, jotoeri commented on docs/DataStructure.md
> +| submitMultiple  | Boolean         |              | If users are only allowed to submit multiple times to the form |
🙈 👍

2022-07-11 19:15 UTC, Chartman123 approved these changes

2022-07-22 16:13 UTC, merged