Feature: Allow shuffling of answer options | Sort options
nextcloud/forms pull request #1271
Opened 2022-07-29 16:37 UTC by susnux

This introduces an question option to randomize the order of the answer options.
Shuffling the order of the answer choices reduces bias in responses.
Implements #1067

If no shuffling is enabled the options are sorted in the order they were
created, as currently they are shown as returned by the database which
is not necessarily sorted. Fixes #1007

2022-07-31 08:20 UTC, jotoeri commented on src/mixins/QuestionMixin.js
> +			return this.shuffleOptions ? [...this.options].sort(() => 0.5 - Math.random()) : [...this.options].sort((a, b) => a.id - b.id)
I'm not sure, if this will solve the issue or probably just shift it. Afaik Prostgresql can reuse ids if a row got deleted. Thus it might happen, that a newly created option has a smaller id than an older one.
This more as a thought. From my side we can also go with this for now.

2022-07-31 20:50 UTC, susnux commented on lib/Db/Question.php
> +		$this->addType('shuffleOptions', 'bool');
Sounds good!
Would you prefer the extra column on the question or a extra table like

<table>
<tr><th colspan=3> question_options</th></tr>
<tr><td>question</td><td>option</td><td>value</td></tr>
</table>

I only ask because the latter option is used by another project I work on and allows querying on the database for that option (e.g. allows filtering on the database layer).

2022-07-31 21:01 UTC, susnux commented on src/mixins/QuestionMixin.js
> +			return this.shuffleOptions ? [...this.options].sort(() => 0.5 - Math.random()) : [...this.options].sort((a, b) => a.id - b.id)
The `SERIAL` data type just uses a `SEQUENCE` so I do not think it will ever reuse IDs.

But we could add a `order` property so the forms author could easily swap the entries or rearrange the order of them.
That would also fix / implement https://github.com/nextcloud/forms/issues/354

2022-07-31 22:23 UTC, Chartman123 commented on src/mixins/QuestionMixin.js
> +			return this.shuffleOptions ? [...this.options].sort(() => 0.5 - Math.random()) : [...this.options].sort((a, b) => a.id - b.id)
Yes, that would be nice to make the order adjustable while already touching the ordering 👍🏻

2022-08-01 07:24 UTC, jotoeri commented on lib/Db/Question.php
> +		$this->addType('shuffleOptions', 'bool');
Uhhm, i think i would for now go with a column on the questions-table, that should suffice, i think.

2022-08-01 07:33 UTC, Chartman123 commented on src/mixins/QuestionMixin.js
> +			return this.shuffleOptions ? [...this.options].sort(() => 0.5 - Math.random()) : [...this.options].sort((a, b) => a.id - b.id)
We could rely on this here: https://github.com/SortableJS/Vue.Draggable

Or are there any other Nextcloud apps that already have an UI for re-ordering records of a list?

2022-08-01 08:42 UTC, susnux commented on src/mixins/QuestionMixin.js
> +			return this.shuffleOptions ? [...this.options].sort(() => 0.5 - Math.random()) : [...this.options].sort((a, b) => a.id - b.id)
> We could rely on this here: https://github.com/SortableJS/Vue.Draggable

Yes that is nice and already a dependency of forms, I will try to rewrite this PR to comply with the comments :)

2022-08-01 19:59 UTC, jotoeri commented on src/mixins/QuestionMixin.js
> +			return this.shuffleOptions ? [...this.options].sort(() => 0.5 - Math.random()) : [...this.options].sort((a, b) => a.id - b.id)
❤️

Just as an idea, that came to my mind: Having the draggable-icon as a hover on the checkbox/radio dummys i could imagine of a way without UI Overload, but sufficiently intuitive. 🤔 @jancborchardt Any idea for a good UI to drag options around?

2022-08-31 18:48 UTC, susnux commented on lib/Db/Question.php
> +		$this->addType('shuffleOptions', 'bool');
Changed it accordingly

2022-08-31 18:49 UTC, susnux commented on CHANGELOG.md
> +### Fixed
Ah thank you, reverted that change :)

2022-08-31 20:18 UTC, susnux commented on src/mixins/QuestionMixin.js
> +			return this.shuffleOptions ? [...this.options].sort(() => 0.5 - Math.random()) : [...this.options].sort((a, b) => a.id - b.id)
I think it is better to postpone this, as it is better suited in a following, separate, pull request. Or what do you think?

2022-08-31 20:45 UTC, Chartman123 commented on src/mixins/QuestionMixin.js
> +			return this.shuffleOptions ? [...this.options].sort(() => 0.5 - Math.random()) : [...this.options].sort((a, b) => a.id - b.id)
Fine by me 🙂

2022-09-01 08:01 UTC, susnux commented on src/mixins/QuestionMixin.js
> +			return this.shuffleOptions ? [...this.options].sort(() => 0.5 - Math.random()) : [...this.options].sort((a, b) => a.id - b.id)
Ok than this PR is ready to be reviewed and later on I will submit an other one providing reorder support based on this

2022-09-01 19:30 UTC, jotoeri commented on lib/Migration/Version030000Date20220831195000.php
> + * @copyright Copyright (c) 2022
You can add your own name there, if you want! 😉

2022-09-01 19:32 UTC, jotoeri commented on lib/Migration/Version030000Date20220831195000.php
> +	// Types::JSON is only available starting with NC24, we still support NC22
Oh, nice, didn't know that! 🚀

2022-09-01 19:44 UTC, susnux commented on lib/Migration/Version030000Date20220831195000.php
> + * @copyright Copyright (c) 2022
If you want me to do it, I can add it but having my name somewhere is not important for me^^

2022-09-01 19:48 UTC, jotoeri approved these changes
Should be fine, i think 🤔

2022-09-01 19:51 UTC, jotoeri commented on lib/Migration/Version030000Date20220831195000.php
> + * @copyright Copyright (c) 2022
Haha, i'm no lawyer, if i think about, if a Copyright should have somebody owning the right 🤔
But don't care, fine by me without.

2022-09-01 19:56 UTC, jotoeri requested changes
Argh, sorry, i was too fast pushing the button.
Just getting this on console, when adding a new question:
![grafik](https://user-images.githubusercontent.com/47433654/188000975-4d05e574-541c-4244-80b5-4743eaccde1e.png)

2022-09-02 09:22 UTC, susnux commented
> Just getting this on console, when adding a new question

Oh yes that happens if there are no settings as the empty array would be serialized as an array instead of an object (assoc. array). This is now fixed.

2022-09-02 09:23 UTC, susnux commented on lib/Migration/Version030000Date20220831195000.php
> + * @copyright Copyright (c) 2022
Added it

2022-09-05 16:10 UTC, jotoeri commented
Top 👍 
Just one more thing i found now:
When checking/unchecking the Shuffle-Checkbox, we should update the computed property of `sortedOptions`. Currently, this only takes effect after reloading the page (while editing the form).

2022-09-05 16:50 UTC, susnux commented
Hm while editing (at least in the editing view) options should not be shuffled (only in the submit view).
But I will test this as soon as I got some time for preparing a test env, as currently master is broken (due to `nextcloud-eventbus` 3.0.1 dependency of `nextcloud-vue` which is already fixed but 3.0.2 is not released)

2022-09-05 18:23 UTC, jotoeri commented
> Hm while editing (at least in the editing view) options should not be shuffled (only in the submit view).

When editing a single question, i'm totally with you. Then they should be ordered.
But on Form-Editing, when not editing a single question (i.e. Within Create.vue, but `edit=false` of Question.vue), the options are currently unsorted (if set). I think that is fine, as this situation should indicate how the final form looks like, but it should also be reactive, so when unchecking the shuffle, then the options are directly shown as sorted (and the other way round).

> due to nextcloud-eventbus 3.0.1 dependency of nextcloud-vue which is already fixed but 3.0.2 is not released

Do you know `npm link`? You can relatively quickly just clone eventbus master, ci, build, link and then link `@nextcloud/event-bus` on forms. Then it works with current master, so you can use it already. 😉

2022-09-06 11:24 UTC, susnux commented
> When checking/unchecking the Shuffle-Checkbox, we should update the computed property of `sortedOptions`. Currently, this only takes effect after reloading the page (while editing the form).

Fixed that.

One general thing I noticed: Currently every interaction is debounced, resulting in a slight UI latency. Would it not be smoother to just debounce the request to the server? (As the UI is currently also not checking the request for success, meaning there is no rollback if that request failed).

2022-09-06 19:50 UTC, jotoeri reviewed
- Old Questions are not loaded/shown (i.e. Questions with `ExtraSettingsJson = NULL`)
- The way of sorting is quite biased, no? Can we get to a Fisher-Yates here? Should be of same Order, but much more effective.

- Can you please test it on your own properly? Takes also quite much time for me, to do this...

2022-09-06 20:28 UTC, jotoeri commented
> One general thing I noticed: Currently every interaction is debounced, resulting in a slight UI latency.

Hmm, i don't think the delay is much of a problem. It is anyways only visible on the two boolean switches and if we fix the actions to be inside of the Editing-Mode, then it even won't be visible that much. (#1329) I also have in mind, that chaning this would also increase the load on the browser due to permanently updating and triggering corresponding reactivities.

2022-09-06 21:39 UTC, susnux commented
@jotoeri Fixed your comments. Sorry for the inconvenience,  I will try to test better.

2022-09-08 21:41 UTC, jotoeri approved these changes
Should be fine now. :+1:

2022-09-11 20:30 UTC, jotoeri commented
@Chartman123 wanna double-check here? :wink:

2022-09-11 22:14 UTC, Chartman123 commented on lib/Db/Question.php
> +	}
I get a warning/error in the browser console:

```
[Vue warn]: Invalid prop: type check failed for prop "extraSettings". Expected Object, got Array 
```

Probably because of using arrays here and an object there: https://github.com/nextcloud/forms/blob/217d12a63cc7dd5f7032068794db7a9dbc296088/src/mixins/QuestionMixin.js#L112-L116

2022-09-11 22:16 UTC, Chartman123 commented on lib/Db/Question.php
> +	}
Basically the same as @jotoeri's comment here: https://github.com/nextcloud/forms/pull/1271#pullrequestreview-1093979213

2022-09-13 18:43 UTC, susnux commented on lib/Db/Question.php
> +	}
That are associative arrays for php but objects for js (`JSON_FORCE_OBJECT` for the encode part and `associative=true` for the decode part).

Are you sure you are on hash 217d12a63cc7dd5f7032068794db7a9dbc296088 ?

2022-09-13 19:28 UTC, Chartman123 commented on lib/Db/Question.php
> +	}
Yes, did a double check right now: 

![image](https://user-images.githubusercontent.com/16020496/189992159-80f90403-66a5-4b9b-ae3b-4f59a9d9f4a0.png)

2022-09-16 19:22 UTC, Chartman123 commented on lib/Db/Question.php
> +	}
@susnux As far as I understand the associative=true returns an array if the json is null... That would totally explain the error in the first place: It appears for questions not having extraSettings. The frontend however expects an object...

![grafik](https://user-images.githubusercontent.com/16020496/190715116-69688a75-4649-4a16-aa50-b1c7ba552e99.png)

2022-09-16 19:44 UTC, Chartman123 commented on lib/Db/Question.php
> +	}
```
	public function getExtraSettings(): object {
		return json_decode($this->getExtraSettingsJson() ?: '{}');
	}
```
This way it works fine for me...

2022-09-19 23:09 UTC, susnux commented on lib/Db/Question.php
> +	}
> This way it works fine for me...

Yes that is working, I now changed the code accordingly.

2022-09-20 05:39 UTC, Chartman123 approved these changes

2022-09-20 11:14 UTC, merged