Implement warning when leaving an unsubmitted form
nextcloud/forms pull request #1310
Opened 2022-08-23 18:05 UTC by Chartman123

Fixes #319 by adding a warning

Signed-off-by: Christian Hartmann <chris-hartmann@gmx.de>

2022-08-23 18:09 UTC, Chartman123 commented
@jotoeri any ideas why the custom message isn't shown in the window.confirm() dialog?

2022-08-26 16:39 UTC, jotoeri commented
Seems like just `confirm` should work. But to be honest, i currently can't tell you exactly, why. :laughing:

https://github.com/nextcloud/forms/blob/6c257edeea2231aeb55f1b62ab85dbb49d6ecef7/src/components/AppNavigationForm.vue#L207

2022-08-26 18:55 UTC, Chartman123 commented
@jotoeri Tried it with just confirm() but doesn't work either... Even with static text. Did just research and it seems that it doesn't accept custom text for the onbeforeunload event

2022-09-14 14:38 UTC, jotoeri commented
Ok, sorry @Chartman123 i checked it once before quickly, but i definitely have not time to get into detail currently. Needs probably to be postponed.

2022-09-14 15:04 UTC, Chartman123 commented
No problem, I think the design parts are more important for 3.0 than this here :)

2022-12-28 13:12 UTC, susnux commented
`confirm` and `alert` are not allowed within `beforeunload`.
Also all browser dropped support for custom messages, so you only can use the default one.


    Chrome removed support for custom message in ver 51
    Opera removed support for custom message in ver 38
    Firefox removed support for custom message in ver 44.0
    Safari removed support for custom message in ver 9.1

2022-12-28 13:16 UTC, Chartman123 commented
Yes, that's true. I'm currently trying to move the warning to a NcModal like in the Cookbook app... This should at least work for leaving a form without closing the window/tab.

2023-06-24 18:29 UTC, susnux requested changes
Currently every time you open the submit view a confirmation dialog is shown, see code comment.

Moreover if you click to stay on the site, an error is thrown in the console because the navigation gets canceled (as requested) by the navigation guard.
So we should add a catch block to the `router.push` calls on the `TopBar` component and ignore every navigation guard related errors.

2023-06-24 18:29 UTC, susnux commented on src/views/Submit.vue
> +                && !this.confirmLeavingPage()
This will even show the dialog if there are *no* unsaved changes, even if you simply in the submit view of your own form for previewing and want to switch back to edit view.
I would suggest to check if there are any answers already like this

```suggestion
				!this.submitForm
				&& Object.keys(this.answers).length > 0
				&& !this.confirmLeavingPage()
```

2023-06-24 21:41 UTC, Chartman123 commented
@susnux Thanks for your input :) I'm also planning to move the warning to a modal. If you want, you can help me there. Everytime I tried it ended up being even worse 😆

2023-09-30 21:41 UTC, Chartman123 commented
@susnux I think I got this working as expected right now. I think we should merge this without the modal right now, so that we can take it as a basis for @hamza221's PR regarding the local storage.

2023-10-16 10:39 UTC, susnux commented on src/views/Submit.vue
> +     */
```suggestion
	 * This is used to confirm that the user wants to leave the page
	 * if the form is unsubmitted.
	 */
```

Mix of tab and spaces

2023-10-16 10:50 UTC, susnux requested changes

2023-10-16 10:50 UTC, susnux commented on src/views/Submit.vue
> +		// beforeRouteLeave is called when the static route changes.
Comment is about "beforeRouteLeave" but "beforeRouteUpdate" is used, I think the comment is wrong as "beforeRouteUpdate" seems to be the proper guard?

2023-10-16 10:50 UTC, susnux commented on src/views/Submit.vue
> +		return false
This seems to be wrong, in the unload event listener you have:
`if (confirmLeaveForm) then cancel`

But here it is reversed, I would stick with this logic here as "confirmLeave" sounds like it is confirmed to leave if true, so if true -> leave. Otherwise cancel.

Also we still use vue-router 3 so the syntax should be:
```suggestion
		if (this.confirmLeaveForm()) {
			next()
		}

		next(false)
```

2023-10-16 10:50 UTC, susnux commented on src/views/Submit.vue
> +			if (this.confirmLeaveForm()) {
See above, the logic seems inverted, if leaving is confirmed we should *not* cancel the event.
```suggestion
			if (!this.confirmLeaveForm()) {
```

2023-10-16 10:50 UTC, susnux commented on src/views/Submit.vue
> +			)
See above.
It sounds like leaving is confirmed, so we should return whenever the navigation should continue and false if we want to cancel the navigation.

```suggestion
		/**
		Check if the form contains unsaved changes, returns true if the the form can be leaved safely, false if the navigation should be canceled.
		 */
		confirmLeaveForm() {
			return (
				this.submitForm
				|| Object.keys(this.answers).length === 0
				|| confirm(t('forms', 'You have unsaved changes! Do you still want to leave?'))
			)
```

2023-10-16 10:50 UTC, susnux commented on src/views/Submit.vue
> +			submitForm: false,
```suggestion
			/** Submit state of the form, true if changes are already submitted */
			submitForm: false,
```

Some kind of documentation would be good as the name is not that self explanatory.

2023-10-16 10:51 UTC, Chartman123 commented on src/views/Submit.vue
> +     */
Oh, some copy paste leftovers... 🙈

2023-10-16 10:54 UTC, Chartman123 commented on src/views/Submit.vue
> +		// beforeRouteLeave is called when the static route changes.
Yes, beforeRouteLeave doesn't work if you work with parameters in the router path. So I'll change the comment here

2023-10-16 11:52 UTC, Chartman123 commented on src/views/Submit.vue
> +		return false
Did you already consider reversing the logic in this suggestion? Or shouldn't it be !this.confirmLeaveForm() then?

2023-10-16 12:27 UTC, susnux commented on src/views/Submit.vue
> +		return false
All suggestions were based on the reversed logic, meaning confirmLeaveForm return true if you should continue with the navigation.

So here is no negation needed

2023-10-16 17:54 UTC, susnux commented on src/views/Submit.vue
> +	},
```suggestion
		// This navigation guard is called when the route parameters changed (e.g. form hash)
		// continue with the navigation if there are no changes or the user confirms to leave the form
		if (this.confirmLeaveForm()) {
			next()
		} else {
			// Otherwise cancel the navigation
			next(false)
		}
	},

	beforeRouteLeave(to, from, next) {
		// This navigation guard is called when the route changed and a new view should be shown
		// continue with the navigation if there are no changes or the user confirms to leave the form
		if (this.confirmLeaveForm()) {
			next()
		} else {
			// Otherwise cancel the navigation
			next(false)
		}
	},
```

After testing this PR: We need both route update and route leave. Otherwise not all cases are handled.

2023-10-16 18:34 UTC, susnux approved these changes
Tested and works now perfectly!

2023-10-16 18:34 UTC, merged