Allow embedding forms within other websites
nextcloud/forms pull request #1353
Opened 2022-09-21 18:02 UTC by susnux

* Resolves #324 

* Add embedded endpoint for page controller and allow inserting submissions without CSFR as anonymous submissions for public shares.
* Added sub-menu entry for copying the embedding code to the clipboard and added documentation on how to use the embedded view.
* Switched to `vue-clipboard2` to allow copying to clipboard from sub-menu entry (allows setting a container for the copy action).

2022-09-22 19:16 UTC, jotoeri commented
Hmm, i'm not sure, if tweaking the csp is a good idea here. I would need to dig into that to properly judge it. Maybe @ChristophWurst or @nickvergessen could give a comment on that, if they find some time.

Probably also to allow the cors-requests now could allow to make it work without the csp stuff. CORS should work now with latest server 25. #1139
I personally have unfortunately no time for this until at least november. Sorry for that.

2022-09-22 23:09 UTC, susnux commented
> i'm not sure, if tweaking the csp is a good idea here

At least that is what appointments and calendar do (I draw inspiration from them).

With this changes CSFR protection is disabled for public shares, but at least you can not assign responses to an specific user, because if the CSFR token does not match (which happens if you embed the form) the responses are assigned to anonymous.


> I personally have unfortunately no time for this until at least november. Sorry for that.

No problem :)

2022-09-23 05:52 UTC, nickvergessen commented
Sorry, that's not my area of expertise

2022-10-17 14:55 UTC, Chartman123 requested changes

2022-10-17 14:55 UTC, Chartman123 commented on docs/Embedding.md
> +For example if want the form to fill out the frame you can use this:
```suggestion
The embedded form provides the `app-forms-embedded` class, so you can apply your styles.\
For example if you want the form to fill out the frame you can use this:
```

2022-10-25 21:32 UTC, Chartman123 commented
I think that you should try to further improve the styling of the embedded form. I opened the embedded route in a maximized browser window and got the following result:

![grafik](https://user-images.githubusercontent.com/16020496/197885742-5c0805e2-bf86-4746-b23d-fc0313286ce6.png)

For the embedded view, I'd suggest to remove the background and the rounded corners and only show the app content itself. Furthermore I'd suggest to keep the width of the form content the way we have it inside Nextcloud or for the public view 🙂

2022-10-25 22:46 UTC, susnux commented
> For the embedded view, I'd suggest to remove the background and the rounded corners and only show the app content itself.

That is already documented in the `Embedding.md":
```
#content-vue.app-forms-embedded {
    width: 100%;
    height: 100%;
    border-radius: 0;
    margin: 0;
}
``` 

But I could change it to be the default.

> Furthermore I'd suggest to keep the width of the form content the way we have it inside Nextcloud or for the public view

The only difference to the public view is: No width limit (so taking 100%), that is also why it is not centered anymore.
I did this so the view is bound to the `iframe` size, as you would control the size and alignment normally by the `iframe` when embedding.

2022-12-24 11:08 UTC, susnux commented
@Chartman123 Fixed that by removing the background on the embedded view by default but still using our styling on the form.

![screenshot](https://user-images.githubusercontent.com/1855448/209433112-a7710c28-a3d7-4894-ab2a-a71e1b83af5b.png)

2022-12-24 11:12 UTC, Chartman123 commented
Nice work :) I think this way it can be embedded much nicer into other websites

2022-12-25 20:54 UTC, Chartman123 approved these changes
Some small changes 🙂  And you could try to add some more tests for the PHP additions 👍🏻

2022-12-25 20:54 UTC, Chartman123 commented on css/embedded.css
> +}
```suggestion
body {
	background-color: var(--color-main-background) !important;
	background-image: none !important;
}

```

Some small improvements here: missing space and missing new line at the end of the file :)

2023-01-22 15:42 UTC, susnux commented
For the failing unit test I need some feedback @jotoeri :

I "fixed" this so it works exactly as on the main branch, so no security changes, but there is a different underlying problem:

Currently the `insertSubmission` endpoint is vulnerable to CSRF attacks.

For `OCSController` the CSRF checks are disabled by default[¹](https://github.com/nextcloud/server/blob/master/lib/private/AppFramework/Middleware/Security/SecurityMiddleware.php#L208).
Be we have set `@CORS` which enforces basic auth, to prevent CSRF attacks, but this is disabled when setting `@PublicPage`[²](https://github.com/nextcloud/server/blob/master/lib/private/AppFramework/Middleware/Security/CORSMiddleware.php#L86) which is set on `insertSubmission`.

So if I am right this means currently it is possible to insert submissions using session authentication which is vulnerable for CSRF. I do not see a simple solution besides using two endpoints: One for users (with `@CORS` without `@PublicPage`) and one for anonymous (with both). But maybe I am missing something?

This is unrelated to this PR, but I think this should be discussed.

2023-01-25 13:07 UTC, Chartman123 commented on docs/Embedding.md
> +This is done as accessing the document within an `iframe` is no possible if not on the same domain.
```suggestion
This is done as accessing the document within an `iframe` is not possible if not on the same domain.
```

2023-01-25 14:02 UTC, susnux commented
Added a message event to allow parent windows to resize the `iframe` to match its content (as direct access is forbidden if embedded from a different domain).

(from user feedback)

2023-02-01 21:26 UTC, Chartman123 commented
@susnux where did the removal of the clipboard related stuff from?

2023-02-01 22:53 UTC, susnux commented
> @susnux where did the removal of the clipboard related stuff come from?

I remember copying the embedding code was not possible, because of some bugs, but it seems line v-clipboard got some updates after 4 year (there is a release from December), I will try if it works now.

2023-02-02 06:42 UTC, Chartman123 commented
Ah ok, then it should also be OK, if we don't need this code anywhere else 👍🏻

2023-02-02 14:24 UTC, susnux commented
I split the copying related change to this PR https://github.com/nextcloud/forms/pull/1478
I will then rebase this onto that PR, I think this is much cleaner.

2023-02-02 16:18 UTC, susnux commented
> I split the copying related change to this PR #1478 I will then rebase this onto that PR, I think this is much cleaner.

Rebased, much cleaner now

2023-02-13 11:50 UTC, jotoeri reviewed
So -  now i got to this one.
- A few comments are in the code.
- Generally, i think we shouldnt have the embedding active by default on share links. So some kind of setting to allow embedding would be good. Maybe UI-wise it could also be a nice way to have a button like "Convert to embedding link" or sth. like that.
- Submit currently doesn't work, since csrf check fails, even that a token is provided. Needs further investigation, but i can also have a look when i find some time 🤔

2023-02-13 11:50 UTC, jotoeri commented on docs/Embedding.md
> +```scss
Did you test that? I'm not sure, if scss insertion is working with the customcss app...

2023-02-13 11:50 UTC, jotoeri commented on lib/Controller/PageController.php
> +	 * @NoSameSiteCookieRequired
Not necessary.

2023-02-13 13:40 UTC, susnux commented on src/components/SidebarTabs/SharingSidebarTab.vue
> +import IconCodeBrackets from 'vue-material-design-icons/CodeBrackets.vue'
This is the icon other apps already use for embedding code, e.g. the Calendar app:
https://github.com/nextcloud/calendar/blob/483f45d537806a9ee82db6ba1f9e94a0db58b299/src/components/AppNavigation/EditCalendarModal/PublishCalendar.vue#L93

2023-02-13 15:17 UTC, susnux commented
Thank you for your review, I fixed most of the code comments.

>     * Generally, i think we shouldnt have the embedding active by default on share links. So some kind of setting to allow embedding would be good. Maybe UI-wise it could also be a nice way to have a button like "Convert to embedding link" or sth. like that.

Do you mean admin settings or per form settings for embedding?

>     * Submit currently doesn't work, since csrf check fails, even that a token is provided. Needs further investigation, but i can also have a look when i find some time thinking

I can not confirm this, we already use this as a custom "preview" version and submitting works as expected (anonymous & logged in).

2023-02-14 10:26 UTC, jotoeri commented
> Do you mean admin settings or per form settings for embedding?

Admin Setting would be a nice thing, but that's separate then.
What i meant was more like per link. So that not just every link is by default usable for embedding, but you have to activate that. Could be just a checkbox to allow embedding per share link.
UI-wise it would probably be a bit nicer to have instead of the checkbox a convert-button, that converts the whole share-link line into an embedding-link line, probobly with the resp. icon and then copying the embedding code by default on the copy-button.

But as said - the main though was, that not just every link is by default usable by everybody to embed it somewhere.

2023-02-14 10:29 UTC, jotoeri commented on src/components/SidebarTabs/SharingSidebarTab.vue
> +import IconCodeBrackets from 'vue-material-design-icons/CodeBrackets.vue'
😕 👍 🤷‍♂️

2023-02-14 10:56 UTC, Chartman123 commented on src/components/SidebarTabs/SharingSidebarTab.vue
> +import IconCodeBrackets from 'vue-material-design-icons/CodeBrackets.vue'
Perhaps something to talk about in the c.nc.c Design team?

2023-02-14 12:28 UTC, susnux commented
> I can not confirm this, we already use this feature and submitting works as expected (anonymous & logged in).

I have to revoke my statement: I now can reproduce this:
It works because cloud and embedding website are on the same site, but if you try to embed on a different site you will get CORS issues.
Also if you are currently logged in the embedding view does not work either because of same site cookie.
I currently think the CSRF issues happen because you get a csrf token from the API, but the further API requests do not include the session (because the session is stored in a same site cookie which only allows same site or safe HTTP requests (`GET`)).

2023-02-15 11:27 UTC, susnux commented
Reset to "developing", I will have to figure out how to fix submissions from embedded pages.

2023-07-28 17:00 UTC, vitormattos commented on src/FormsSubmit.vue
> +	methods: {
```suggestion
	destroyed() {
		unsubscribe('forms:last-updated:set')
	},

	methods: {
```

Unsubscribe the event.

2023-07-28 17:00 UTC, vitormattos commented on src/FormsSubmit.vue
> +		if (this.isEmbedded) {
```suggestion
		if (this.isEmbedded) {
			subscribe('forms:last-updated:set', (id) => {
				window.parent?.postMessage({
					type: 'form-saved',
					payload: {
						id,
					},
				}, '*')
			})
```
To be possible trigger the saved event at window parent

2023-07-28 17:00 UTC, vitormattos commented on docs/Embedding.md
> +	if (event.origin !== "http://your-nextcloud-server.com") {
To be more generic:

```suggestion
	if (event.origin !== window.location.protocol + '//' + window.location.host) {
```

2023-07-28 17:05 UTC, vitormattos commented on src/FormsSubmit.vue
>  			:share-hash="shareHash"
```suggestion
			:share-hash="shareHash"
			:sidebar-opened="!isEmbedded"
```
To prevent the follow error:

![Screenshot_20230728_140444](https://github.com/nextcloud/forms/assets/1079143/8ada673d-0c10-4014-a4dd-6d748954f05a)

2023-07-28 17:31 UTC, susnux commented on docs/Embedding.md
> +	if (event.origin !== "http://your-nextcloud-server.com") {
I do not think this is good here, as it implies your nextcloud instance is running on the same domain as your website.
So having the "fixed" URL there will make it clearer you have to adjust it for you setup (like it will otherwise break if your nextcloud instance is running on `cloud.example.com` but your website is running on `www.example.com`).

2023-07-28 17:32 UTC, susnux commented on src/FormsSubmit.vue
>  			:share-hash="shareHash"
Nice catch!

2023-07-28 20:07 UTC, vitormattos commented on docs/Embedding.md
> +	if (event.origin !== "http://your-nextcloud-server.com") {
Is only an example, can mark as resolved without changes at this point :-)

2024-03-20 14:15 UTC, susnux commented on src/FormsSubmit.vue
> +			this.$nextTick(() => resizeObserver.observe(document.querySelector('.app-forms-embedded form')))
will not work as we do not need the container width but the inner form width

2024-03-20 14:27 UTC, susnux commented
One change to note: The submission insert no longer sets the CSRF annotation, because this is already done by the CORS annotation:
- If a user session is found (logged in) on of the following must succeed:
  - the CSRF check is performed
  - check that basic auth is used

2024-03-21 08:53 UTC, Chartman123 commented on src/components/SidebarTabs/SharingSidebarTab.vue
> +				:class="{ 'share-div--embeddable': isEmbeddingAllowed(share) }">
Why don't you use isEmbeddable here?

2024-03-21 08:56 UTC, Chartman123 commented on src/components/SidebarTabs/SharingSidebarTab.vue
> +		 * @param {{ permissions: string[] }} share
Please add missing JSDoc param

2024-03-21 08:56 UTC, Chartman123 commented on src/mixins/ShareLinkMixin.js
> +		 * @param {{ shareType: number, permissions: string[] }} share
Please add missing JSDoc param

2024-03-21 08:58 UTC, Chartman123 commented on src/mixins/ShareLinkMixin.js
> -			event.target.focus()
Is this no longer needed?

2024-03-21 09:00 UTC, Chartman123 commented on tests/Unit/Controller/ShareApiControllerTest.php
> +
why a new line here?

2024-03-21 18:07 UTC, susnux commented on src/components/SidebarTabs/SharingSidebarTab.vue
> +				:class="{ 'share-div--embeddable': isEmbeddingAllowed(share) }">
It does not work on the element were you "set" it, it will still use the value from the loop before

2024-03-21 18:10 UTC, Chartman123 commented on src/components/SidebarTabs/SharingSidebarTab.vue
> +				:class="{ 'share-div--embeddable': isEmbeddingAllowed(share) }">
Thanks for the explanation :)

2024-03-22 12:12 UTC, Chartman123 reviewed
I fixed a few typos regarding the new `embed` permission. :)

2024-03-22 12:12 UTC, Chartman123 commented on lib/Constants.php
> +	public const PERMISSION_EMBEDD = 'embedd';
```suggestion
	public const PERMISSION_EMBED = 'embed';
```

2024-03-22 12:12 UTC, Chartman123 commented on lib/Constants.php
> +		self::PERMISSION_EMBEDD,
```suggestion
		self::PERMISSION_EMBED,
```

2024-03-22 12:12 UTC, Chartman123 commented on lib/Controller/PageController.php
> +			if (!in_array(Constants::PERMISSION_EMBEDD, $share->getPermissions())) {
```suggestion
			if (!in_array(Constants::PERMISSION_EMBED, $share->getPermissions())) {
```

2024-03-22 12:12 UTC, Chartman123 commented on src/components/SidebarTabs/SharingSidebarTab.vue
> +			this.updateShare({ ...share, permissions: [...share.permissions, this.PERMISSION_TYPES.PERMISSION_EMBEDD] })
```suggestion
			this.updateShare({ ...share, permissions: [...share.permissions, this.PERMISSION_TYPES.PERMISSION_EMBED] })
```

2024-03-22 12:12 UTC, Chartman123 commented on src/mixins/PermissionTypes.js
> +				PERMISSION_EMBEDD: 'embedd',
```suggestion
				PERMISSION_EMBED: 'embed',
```

2024-03-22 12:12 UTC, Chartman123 commented on src/mixins/ShareLinkMixin.js
> +			return share.shareType === this.SHARE_TYPES.SHARE_TYPE_LINK && share.permissions?.includes(this.PERMISSION_TYPES.PERMISSION_EMBEDD)
```suggestion
			return share.shareType === this.SHARE_TYPES.SHARE_TYPE_LINK && share.permissions?.includes(this.PERMISSION_TYPES.PERMISSION_EMBED)
```

2024-03-22 12:12 UTC, Chartman123 commented on tests/Unit/Controller/ShareApiControllerTest.php
> +					'permissions' => [Constants::PERMISSION_SUBMIT, Constants::PERMISSION_EMBEDD]
```suggestion
					'permissions' => [Constants::PERMISSION_SUBMIT, Constants::PERMISSION_EMBED]
```

2024-03-22 16:47 UTC, Chartman123 approved these changes

2024-03-22 16:48 UTC, Chartman123 commented
@susnux After rebasing it here via Github, we lost the DCO check ;) Could you please do another rebase and push it again? After that I think we're good to go :)

2024-03-22 18:28 UTC, merged

2024-03-22 19:38 UTC, whoamiafterall commented
Nice - i'm looking forward to this. When will be the next release?

2024-03-22 20:19 UTC, susnux commented
Thank you :)

> When will be the next release?

Somewhen before Nextcloud 29 release, we do not have a strict schedule for the next release.