Submission Files can be linked and unlinked to form
nextcloud/forms pull request #1403
Opened 2022-11-08 19:35 UTC by hamza221

Signed-off-by: hamza mahjoubi <hamzamahjoubi221@gmail.com>

2022-11-08 19:49 UTC, hamza221 commented
I'm aware of the failing checks 🥲, I'll acknowledge them once I get feedback. I'll work on other features in the meantime

2022-11-10 23:14 UTC, Chartman123 commented
@hamza221 Had a quick look at the code and think this is the way to go here. However, I didn't have the time to have a closer look. One thing I saw: I think that you can stay with the API v2 here, as we're not breaking compatibility with this change.

2022-11-10 23:29 UTC, hamza221 commented
Yes, I was actually not sure about that, I'll change it in my next commit

2022-11-15 18:45 UTC, hamza221 commented
FYI: Before testing this branch migration version.  3000Date20221101205756 should be executed 
Navigate to server folder and run ` php occ migrations:execute forms 3000Date20221101205756`

2022-11-15 18:45 UTC, jancborchardt requested changes
Very nice! :) Some changes as discussed:
- [x] Move the "Link to a spreadsheet" entry out of the menu into a button saying "Create spreadsheet", using the "table" icon
- [x] When it says "Open spreadsheet", it can also use the "table" icon instead of folder. Also note fixed capitalization from "spreadSheet" ;)
- [x] The "Unlink spreadsheet" should be the first item in the menu.
- [ ] Check if the file_id can just use VARCHAR(64) instead of 255

2022-11-15 22:12 UTC, Chartman123 commented
What came to my mind regarding the wording: The files are basically csv files and no spreadsheets, aren't they?

2022-11-16 14:54 UTC, jancborchardt commented
@Chartman123 yes they are, but we were thinking that "spreadsheet" is a more human term in this case cause it will then be open-able via Nextcloud Office. :) 

Also, Google Forms calls this functionality "Create spreadsheet".

2022-11-18 07:11 UTC, Chartman123 commented
> Also, Google Forms calls this functionality "Create spreadsheet".

@jancborchardt Yes, because in their case, they really create a Google Spreadsheet document and not only a CSV ;-) I'm thinking about the users that don't have installed a office solution in their nextcloud...

2022-11-21 15:35 UTC, jancborchardt commented
> > Also, Google Forms calls this functionality "Create spreadsheet".
> 
> @jancborchardt Yes, because in their case, they really create a Google Spreadsheet document and not only a CSV ;-) I'm thinking about the users that don't have installed a office solution in their nextcloud...

Yeah understood – even in that case, it will still work as a spreadsheet. :) It’s just that it’s a more accessible name than "CSV" for a function that will be now very visible in the interface as a button.

2022-12-04 13:26 UTC, Chartman123 requested changes

2022-12-04 13:26 UTC, Chartman123 commented on lib/Controller/ApiController.php
> +		}
This should only be executed if there is a file linked

2022-12-04 13:26 UTC, Chartman123 commented on lib/Migration/Version3000Date20221101205756.php
> +		]);
@jotoeri should we move the file path and the file id to a JSON field "extra_settings_json" just like for the questions?

And @hamza221 could you please rename the migration file to match the names of the other migrations? So probably Version030100...

2022-12-04 13:26 UTC, Chartman123 commented on lib/Controller/ApiController.php
> +	}
I'm not quite sure how the file operations are handled within Nextcloud, but I think that we must make sure that the given path is accessible and writeable by the user.

2022-12-05 12:19 UTC, hamza221 commented on lib/Controller/ApiController.php
> +	}
It is set from the file picker, So it is already being set by the user. If I got your comment correctly

2022-12-05 12:55 UTC, Chartman123 commented on lib/Controller/ApiController.php
> +	}
Yes, but you can also directly call the API and then you have to make sure that the path exists and the user can access it.

2023-03-24 13:34 UTC, jdaviescoates commented
> they really create a Google Spreadsheet

That's what #5 is about too " Write responses into spreadsheet (like Google Forms) #5 "

That's the feature that is needed imho.

2023-08-21 14:19 UTC, AIlkiv commented
Hello!

1. What is blocking this pull request?
2. I believe it would be more practical to save it in ODT format, as CSV cannot edited in Office.
3. It would be beneficial to append to the file instead of overwriting it. For instance, the administrator could mark the answers as processed/not processed in a separate column.

2023-08-21 15:10 UTC, Chartman123 commented
Hi @AIlkiv
> 1. What is blocking this pull request?
Probably time for working on it 
> 2. I believe it would be more practical to save it in ODT format, as CSV cannot edited in Office.
CSV can be imported in other spreadsheet applications and is the easiest to achieve as it's purely text based.
> 3. It would be beneficial to append to the file instead of overwriting it. For instance, the administrator could mark the answers as processed/not processed in a separate column.
I fully agree on this 👍🏻

2023-11-08 00:10 UTC, closed without merging