transfer ownership of a form
nextcloud/forms pull request #1416
Opened 2022-11-26 20:16 UTC by hamza221

Signed-off-by: hamza221 <hamzamahjoubi221@gmail.com>

2022-11-27 22:45 UTC, Chartman123 requested changes
I get an error when I actually transfer the form to another user. Probably because you're staying in the same route after the transfer and therefore on a form for which the current user doesn't have edit permissions anymore.

Second, a little loading indicator would be nice between selecting a user and showing the modal. It takes some time (around 3 to 5 seconds for me) between choosing the user and the modal being shown.

2022-11-27 22:45 UTC, Chartman123 commented on src/Forms.vue
> +			title="Transfer Ownership"
ownership should not be capitalized here

2022-11-27 22:45 UTC, Chartman123 commented on src/Forms.vue
> +				{{ t('forms', 'Are you sure you want to tranfer Ownership of this Form to ') }} {{ tranferData.displayName }}?
ownership should not be capitalized here

2022-11-28 14:16 UTC, hamza221 commented on src/Forms.vue
> +			title="Transfer Ownership"
Can you please the console output when opening the modal, there's a vue warn that I couldn't solve. Maybe you've seen it before and can help me figure out the cause

2022-12-01 17:02 UTC, jancborchardt requested changes
Nice! Some design details:
- [x] This setting should be all the way on the bottom of the settings, since it’s the least common one
- [x] It would be better as a Button than a switch
- [x] The label "Transfer ownership" is clearer
- [x] I’d expect the modal to open on button press also for the name input directly, like GitHub does on repository transfers. Then we also only have one modal
   ![image](https://user-images.githubusercontent.com/925062/205113364-a9a915be-560f-4aef-92bb-2b9241480629.png)
- [x] The modal needs a heading, like "Transfer [formname]"
- [x] The buttons are wrongly colored and labeled – "Yes/No" is too inconcrete. Similar to Github, we only need a confirmation button, which is red, and labeled "Transfer [formname] to [username]". For canceling we have the x in the top right
- [ ] The words "ownership", "form" and "cancelled" need to be lowercase when part of a sentence

2022-12-07 16:33 UTC, hamza221 commented
This last commit addresses all the mentioned issues but loading because I didn't find a straightforward way to address it since the event is triggered in one component "SettingsSidebarTab" and handled in another one "Forms".

I'll get back to it. But currently writing my thesis ( I Have to submit it on the 10th) so I'm trying to gain time by getting all PRs to a state where I can write documentation about them.  and I'll get all of them to a merging state after the 10th.

2022-12-07 17:32 UTC, jotoeri commented
Can you create a separate component for the transfer? Should be good, if it just contains the Button and the Modal, including all corresponding procedures. Then you can just load the new component on the sidebar.

> But currently writing my thesis

Good luck! 🤞 💪

2022-12-20 21:22 UTC, hamza221 commented
Per @jotoeri  recommendation I created a separate component for ownership transfer. I'll add the missing tests later this week

2022-12-26 20:18 UTC, Chartman123 commented on src/components/SidebarTabs/TransferOwnership.vue
> +			showError(t('forms', 'Ownership transfer was Cancelled'))
```suggestion
			showError(t('forms', 'Ownership transfer was cancelled'))
```
Lower case "c" :)

2022-12-26 20:29 UTC, Chartman123 commented on src/components/SidebarTabs/TransferOwnership.vue
> +						{{ t('forms', 'Type ') }} {{ confirmationString }} {{ t('forms', ' to confirm') }}
```suggestion
						{{ t('forms', 'Type ') }} <strong>{{ confirmationString }}</strong> {{ t('forms', ' to confirm') }}
```
I think we should highlight the text that the user has to type more.

2022-12-26 20:31 UTC, Chartman123 commented
@hamza221 The current solution works much smoother than before. Nice job 👍🏻

2023-01-03 22:09 UTC, jotoeri reviewed
Nice @hamza221 :) I still have a bunch of comments here, but that's more since i now commented many small things. Design-wise and css-wise there is also a bit to do still, but maybe @jancborchardt can also help you on this. But in general, it feels like this is on a good way now. :)

A rebase (& squash) would also be good, when you're on it.

2023-01-03 22:09 UTC, jotoeri commented on src/components/SidebarTabs/TransferOwnership.vue
> +}
Just CSS-wise, you could maybe try to get an idea how it is done in the form-header within submit.vue? There it works without sections.

2023-01-03 22:09 UTC, jotoeri commented on src/views/Sidebar.vue
> +		},
Dead code?

2023-01-03 22:11 UTC, jotoeri commented on appinfo/routes.php
> +				'apiVersion' => 'v2'
Ahh, and adding it to the documentation would be good then. But that can be a very last thing. 😉

2023-01-05 10:01 UTC, jotoeri commented on src/components/SidebarTabs/TransferOwnership.vue
> +						{{ t('forms', 'Type ') }} {{ confirmationString }} {{ t('forms', ' to confirm') }}
And if possible, make it able to copy it. 😋

2023-07-21 17:49 UTC, jospoortvliet commented
Hi, just curious - what's still on the todo here? Does it 'just' need another review & approval?

2023-07-21 18:18 UTC, Chartman123 commented
@jospoortvliet I'll have another look at it :)

2023-07-21 21:41 UTC, Chartman123 commented
@hamza221 @jospoortvliet I think there is still a little work to do. On loading the modal the input box has a little glitch:
![grafik](https://github.com/nextcloud/forms/assets/16020496/f8e3010e-8eae-420a-94e9-604d23589b60)

When you closse the recommendation by clicking somewhere else in the modal and then click back into the user selection, everything looks fine.

Another thing that I noticed: When you select a user, the input field should lose the focus so that you don't have to click anywhere else to close the lower part.

And the button to start the transfer only reacts to the "security" input of the form name. It doesn't matter if you have selected a user or not and then of course throws an error in the console when you didn't select a user first.

2023-07-24 09:35 UTC, jospoortvliet commented
awesome! Now, with those fixed, what's missing? The reviews are all implemented, correct? So a final thumbs up and merge?

2023-07-24 09:52 UTC, Chartman123 requested changes
There are still some Lint errors. I would also like to just have another look at the code (mostly naming related).

2023-07-24 09:52 UTC, Chartman123 commented on lib/Controller/ApiController.php
> +	public function ownerTransfer(int $formId, string $uid): DataResponse {
```suggestion
	public function transferOwner(int $formId, string $uid): DataResponse {
```
I think we should change the name here

2023-07-24 09:52 UTC, Chartman123 commented on appinfo/routes.php
> +			'name' => 'api#ownerTransfer',
```suggestion
			'name' => 'api#transferOwner',
```

2023-07-24 09:52 UTC, Chartman123 commented on src/components/SidebarTabs/TransferOwnership.vue
> +			transferData: { formId: null, userId: null, displayName: '' },
This is still open

2023-07-24 09:57 UTC, hamza221 commented
still working on the changes will push my changes in a bit the previous commit was just a rebase

2023-07-24 17:09 UTC, hamza221 commented
I couldn't fix the input glitch, @Chartman123  do you think it might be a bug in NcSelect itself?

2023-07-24 17:22 UTC, Chartman123 commented
It might be related to the order of the rendering. Like if the input field were rendered before the padding of the modal was applied and then the dropdown part were not re-rendered.

2023-07-24 20:20 UTC, Chartman123 commented on src/components/SidebarTabs/TransferOwnership.vue
> +					</div>
Collectives has a nice implementation for the selected users:
https://github.com/nextcloud/collectives/blob/5a69647aef5c537ae3056c1225fa0cd588591918/src/components/Member/MemberPicker.vue#L19-L33

https://nextcloud-vue-components.netlify.app/#/Components/NcUserBubble

2023-07-26 20:32 UTC, Chartman123 commented on appinfo/routes.php
> +				'apiVersion' => 'v2'
Documentation is still missing :)

2023-07-26 20:40 UTC, Chartman123 commented on src/components/SidebarTabs/TransferOwnership.vue
> +					</div>
@hamza221 just another thought about it: do we really need the NcUserBubble? We could also just use NcSelect like in the example here: https://nextcloud-vue-components.netlify.app/#/Components/NcSelect?id=ncselect-1

2023-08-06 13:50 UTC, hamza221 commented on src/components/SidebarTabs/TransferOwnership.vue
> +					</div>
It's already working like the example, I can see how NcUserBubble is unnecessary in this context, I'll just remove it

2023-08-06 14:11 UTC, hamza221 commented
are the failing PHPUnit  related? it show failed 
One or more containers failed to start.

2023-08-06 14:15 UTC, Chartman123 commented
> are the failing PHPUnit  related? it shows: 
> One or more containers failed to start.

At least the OCI job fails more often. For the postgres job, it's the first time I see it failing. I'll try a re-run of the failed jobs

2023-08-06 19:01 UTC, Chartman123 requested changes
I've found a few more things that you could please work on. But overall I think that this is now close to being ready. Please also add the documentation of the API.

The "glitch" with the NcSelect list is now much better but sometimes I still see that the lower part is a little wider than the input field itself.

2023-10-23 20:28 UTC, Chartman123 reviewed
A few more comments. The animation problem seems to be fixed now, too. But the modal changes size when you have selected a user and click back into the field. The cursor looks misplaced, too.

[forms.webm](https://github.com/nextcloud/forms/assets/16020496/039a026a-d66a-4916-a3f2-976790b978b0)

2023-12-09 13:32 UTC, hamza221 commented
> A few more comments. The animation problem seems to be fixed now, too. But the modal changes size when you have selected a user and click back into the field. The cursor looks misplaced, too.
I can't reproduce after the nextcloud/vue bump , @Chartman123  does it still happen on your end?

2023-12-09 13:40 UTC, Chartman123 commented
> I can't reproduce after the nextcloud/vue bump , @Chartman123 does it still happen on your end?

@hamza221 seems fixed upstream, yes 👍🏻  no problems here anymore

2023-12-09 13:42 UTC, Chartman123 commented
`could not invoke event listener TypeError: this.sharedForms[sharedFormIndex] is undefined`

I get the above error after clicking the transfer button in the modal.

2023-12-09 14:44 UTC, hamza221 commented on src/views/Results.vue
> -	.setModal(true)
@susnux  [This is deprecated](https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/911), And I can't build the project with it set.
Should we remove it in this Pr?

2023-12-09 15:24 UTC, hamza221 commented on src/views/Results.vue
> -	.setModal(true)
split in a new Pr https://github.com/nextcloud/forms/pull/1826

2023-12-09 15:31 UTC, Chartman123 approved these changes

2023-12-09 16:10 UTC, susnux requested changes
Nice works! But a few comments.

2023-12-09 16:10 UTC, susnux commented on src/components/SidebarTabs/TransferOwnership.vue
> +		<NcModal :show.sync="showModal"
I would really recommend `NcDialog`.

2023-12-09 16:10 UTC, susnux commented on src/components/SidebarTabs/TransferOwnership.vue
> +						{{ t('forms', 'Please select the account to which you want to transfer ownership"') }}
```suggestion
						{{ t('forms', 'Please select the account to which you want to transfer ownership') }}
```

Extra quote

2023-12-09 16:10 UTC, susnux commented on src/components/SidebarTabs/TransferOwnership.vue
> +					{{ t('forms', 'I understand, transfer this form') }}
Not sure about this sentence here, for github there is a warning before so that you confirm the warning and notes.
I think it might make sense to add text before this like "This can not be undone" or similar.

2023-12-10 16:52 UTC, hamza221 commented
<img width="1440" alt="image" src="https://github.com/nextcloud/forms/assets/40746210/81acecb9-bfb3-4c1e-a71a-7438bd8adc0f">

2023-12-10 17:01 UTC, Chartman123 commented on src/components/SidebarTabs/TransferOwnership.vue
> +					{{ t('forms', 'I understand, transfer this form') }}
> "This can not be undone"

I'm not sure if we really need this here. The action can be undone when the new owner transfers ownership back to the current owner.

2023-12-11 13:50 UTC, Chartman123 commented on src/components/SidebarTabs/TransferOwnership.vue
> +				</h2>
Now that the NcDialog already has this in the title, I would omit it here.

2023-12-11 13:53 UTC, Chartman123 commented on src/components/SidebarTabs/TransferOwnership.vue
> +				</NcButton>
Could you please move this button to the #actions slot?

2023-12-11 18:51 UTC, hamza221 commented on src/components/SidebarTabs/TransferOwnership.vue
> +				</NcButton>
It's already there

2023-12-12 19:46 UTC, susnux approved these changes

2023-12-12 19:48 UTC, susnux commented on appinfo/routes.php
> +			'name' => 'api#transferOwner',
The only thing I do not know if this is needed and we not simply can use the update endpoint and change the owner?

2023-12-12 20:52 UTC, Chartman123 approved these changes

2023-12-12 21:09 UTC, Chartman123 commented on appinfo/routes.php
> +			'name' => 'api#transferOwner',
I'd keep it separate for now. And I'll create a issue as follow up that we need to add a test for this

2023-12-12 21:37 UTC, merged

2024-04-19 18:15 UTC, hbiering commented
I tried to transfer ownership from myself (as admin) to a group. The Group-name was found when I started typing it in the upper field - and the transfer option was enabled when I entered the required (bold) phrase in the second field. But when continuing, I got the error message: "An error occurred while transfering ownership"

Is the transfer option intended to support transfer to User Groups (as the group shows up when you start to type) or is it limited to individual users. Although you can share final results in a spreadsheet the latter is a problem for collaboration in teams.

2024-04-19 18:23 UTC, susnux commented
Ownership is bound to users so the bug is that the search does not limit to users.

2024-04-20 13:16 UTC, susnux commented
Ownership is bound to users so the bug is that the search does not limit to users.