Allow reordering questions using the keyboard
nextcloud/forms pull request #1532
Opened 2023-02-22 01:40 UTC by susnux

### Part 1: Adding missing aria role
Resolves: #1263 
`div`s require a role when `aria-label` is set (see context in linked issue)

### Part 2: Add buttons
Resolves: #317 
Added buttons for changing the order. Buttons can be focused and triggered using the keyboard.
This also preserves the drag and drop handling, but also allows using buttons or the keyboard.

The buttons are only shown if hovered / focused, but they are always accessible for screen readers.

If a button is clicked / triggered the focus is kept on the button (the vanishing focus ring in the following video happens only because disabled buttons from `@nextcloud/vue` do not have a visual focus ring)

https://user-images.githubusercontent.com/1855448/220498206-3a1befaf-6def-45e1-9be7-980e8ee4b277.mp4

2023-02-22 06:59 UTC, jancborchardt requested changes
Very nice enhancement! :) Makes it very obvious and accessible how to reorder, good stuff.

Only one thing: When reordering via these buttons, whether it be via keyboard or mouse click, it would be nice to have a quick animation of the movement using `var(--animation-quick)` or `var(--animation-slow)` depending on what looks better. :)

2023-02-22 14:47 UTC, susnux commented
> Very nice enhancement! :) Makes it very obvious and accessible how to reorder, good stuff.

Thank you :)

> Only one thing: When reordering via these buttons, whether it be via keyboard or mouse click, it would be nice to have a quick animation of the movement using `var(--animation-quick)` or `var(--animation-slow)` depending on what looks better. :)

Done. Added the animation, I choose `slow` because `quick` for long questions looks too "jumpy".


https://user-images.githubusercontent.com/1855448/220657783-6cda0693-8d11-4d95-baa1-de646dce0d8f.mp4

2023-02-22 15:35 UTC, jancborchardt approved these changes
Looks really amazing now @susnux, great work! :)

2023-02-23 20:10 UTC, Chartman123 commented
@susnux I get lots of errors in the browser console like this:

```
[Vue warn]: Invalid prop: type check failed for prop "setReturnFocus". Expected Object, String, Function, Boolean, got HTMLButtonElement 

found in

---> <NcPopover>
       <NcActions>
         <RouterLink>
           <NcListItem>
             <AppNavigationForm> at src/components/AppNavigationForm.vue
               <NcAppNavigation>
                 <NcContent>
                   <Forms> at src/Forms.vue
                     <Root> 2 forms-main.js:134698:21
```

The lower part of the message varies...

And at least for me the focus ring always stays on the ⬇️ button after clicking on it with the mouse. The ⬆️ button doesn't show the ring.

2023-02-23 21:50 UTC, susnux commented
@Chartman123 the errors should be fixed with nextcloud Vue 7.7.0:
https://github.com/nextcloud/nextcloud-vue/pull/3803

2023-02-23 22:19 UTC, Chartman123 commented
@susnux: With nc-vue 7.7 the errors are gone. But now I found some new ones: canMoveUp and canMoveDown are missing in the view mode and thus throwing errors.

```
[Vue warn]: Missing required prop: "canMoveUp"

found in

---> <Question> at src/components/Questions/Question.vue
       <QuestionDropdown> at src/components/Questions/QuestionDropdown.vue
         <NcAppContent>
           <Submit> at src/views/Submit.vue
             <NcContent>
               <Forms> at src/Forms.vue
                 <Root>
```

2023-02-28 12:25 UTC, susnux commented
> With nc-vue 7.7 the errors are gone. But now I found some new ones: canMoveUp and canMoveDown are missing in the view mode and thus throwing errors.

@Chartman123 those issues are resolved. And the focus issue is also resolved.

2023-02-28 12:41 UTC, Chartman123 commented
> > With nc-vue 7.7 the errors are gone. But now I found some new ones: canMoveUp and canMoveDown are missing in the view mode and thus throwing errors.
> 
> @Chartman123 those issues are resolved. And the focus issue is also resolved.

Nice :) I will check it this evening

2023-02-28 15:03 UTC, Chartman123 commented on src/components/Questions/Question.vue
> +			<NcButton ref="buttonU"
```suggestion
			<NcButton ref="buttonUp"
```
shouldn't this be buttonUp?

2023-02-28 15:04 UTC, Chartman123 commented on src/components/Questions/Question.vue
> +			this.$nextTick(() => this.$refs.buttonU.$el.focus())
```suggestion
			this.$nextTick(() => this.$refs.buttonUp.$el.focus())
```
Same here

2023-02-28 21:30 UTC, Chartman123 commented on src/components/Questions/QuestionDate.vue
> -		@delete="onDelete">
Can we remove the onDelete method from Question.vue if you remove it from every question type?

2023-03-05 20:57 UTC, susnux commented on src/components/Questions/QuestionDate.vue
> -		@delete="onDelete">
No. We still need to emit the `delete` event from the `Question`.

I just deleted the `onDelete` from the "parent" questions (like `QuestionDate`), as it is already included within the `v-on="$listeners"`.

2023-03-12 15:16 UTC, jotoeri commented on src/views/Create.vue
> +				<transition-group :move-class="isDragging ? 'nomove' : undefined">
Any reason for that nomove? A transition was desired here (see 200ms on Draggable). - Even that the old transition seems to get broken with this PR, too. 😕

2023-03-12 15:31 UTC, susnux commented on src/views/Create.vue
> +				<transition-group :move-class="isDragging ? 'nomove' : undefined">
If you drag it, a transition looks quite bad as when you drop the question you would expect it to be just where you dropped it and not on its previous position and moving to the new.

2023-03-12 15:39 UTC, jotoeri commented on src/views/Create.vue
> +				<transition-group :move-class="isDragging ? 'nomove' : undefined">
That's true - but while dragging the transition should be maintained as it is on master currently.

2023-04-19 13:52 UTC, jancborchardt commented on src/components/Questions/Question.vue
> +			role="button">
cc accessibility experts @JuliaKirschenheuter @Pytal – what would you recommend?

2023-04-21 23:33 UTC, Pytal commented on src/components/Questions/Question.vue
> +			role="button">
Since reordering can be done via keyboard with the move buttons already then there is already feature parity for keyboard-only users

We can still keep the draggable functionality for mouse users but the `role` and `aria-label` should be removed as they are never read by screenreaders anyways with the non-focusable `div`

2023-10-16 22:45 UTC, susnux commented on src/views/Create.vue
> +				<transition-group :move-class="isDragging ? 'nomove' : undefined">
Fixed

2023-10-16 22:49 UTC, susnux commented on src/components/Questions/Question.vue
> +			role="button">
:+1: removed

2023-10-16 22:51 UTC, susnux commented
- Rebased
- Fixed a11y issues
- Fixed transition for both: Keyboard and mouse sorting


https://github.com/nextcloud/forms/assets/1855448/935cb36d-28c6-46c8-b64d-9b64e359fbe0

2023-10-23 15:33 UTC, susnux commented on src/components/Questions/Question.vue
> +		justify-content: space-around;
I agree, but then we need a `gap` otherwise they are too close. I will go for `12px` :)

2023-10-23 20:34 UTC, Chartman123 approved these changes

2023-10-24 02:01 UTC, merged