Add hover effect to response view switcher
nextcloud/forms pull request #1559
Opened 2023-03-15 13:32 UTC by susnux

I think with a hover effect it looks a bit better:

before | after
---|---
![no hover effect on the switcher](https://user-images.githubusercontent.com/1855448/225323334-b47231d2-8b4c-4779-af60-13195d6430dc.png) | ![with hover effect](https://user-images.githubusercontent.com/1855448/225323360-326a0dfa-7129-497d-93cb-00cc05bb226d.png)

Or maybe better to see on this screen recording:

https://user-images.githubusercontent.com/1855448/225323518-caa2b6a8-3494-4eb9-8a0a-85705c79ab99.mp4

2023-03-15 13:36 UTC, Chartman123 approved these changes

2023-03-15 13:44 UTC, jancborchardt requested changes
Nice! Just one thing, any hover effect should be present for `:focus` as well so it is accessible to people who use keyboard only. :)

2023-03-15 14:23 UTC, susnux commented
> Nice! Just one thing, any hover effect should be present for `:focus` as well so it is accessible to people who use keyboard only. :)

@ jancborchardt thank you! Because of your comment I tried to use keyboard navigation and noticed that it currently did not even work. Not only there was no hover effect but I could no focus the toggle to switch the view!

So I pushed another commit allowing to use keyboard navigation. Now it looks like this when using keyboard navigation:


https://user-images.githubusercontent.com/1855448/225338640-204cd3f0-cf14-472c-9384-93622970519a.mp4

2023-03-15 18:48 UTC, jotoeri commented
Shouldnt we generally change it, so it looks similar to the views-switch? Maybe just a bit smaller than the other one...

2023-03-15 19:17 UTC, susnux commented
> Shouldnt we generally change it, so it looks similar to the views-switch? Maybe just a bit smaller than the other one...

I think this UI was heavily inspired by google forms (see below), so as we have a custom view selector by now we can reuse that of cause.

![google forms selector](https://howtogapps.com/wp-content/uploads/2019/11/google-forms-responses-tab.jpg.webp)

2023-03-15 22:31 UTC, susnux commented
> Shouldnt we generally change it, so it looks similar to the views-switch? Maybe just a bit smaller than the other one...

@jotoeri what do you think about doing it like this?

https://user-images.githubusercontent.com/1855448/225457953-8c3b969d-fa66-44cd-9591-e7f2f174016b.mp4

2023-03-16 19:54 UTC, jotoeri commented
Hmm, yes, at least better than completely different from the other switch. Maybe a bit less in height? And a bit of margin around? 😉 @jancborchardt ?

2023-03-17 12:30 UTC, susnux commented
> Maybe a bit less in height?

If I am right the current height of 44px is already the minimum size in terms of accessibility? (At least from [WCAG](https://w3c.github.io/wcag/understanding/target-size-enhanced))

> And a bit of margin around?

Of cause, that screen recording was just a quick mockup.

2023-04-02 15:06 UTC, jotoeri commented
Superseded by #1576

2023-04-02 15:06 UTC, closed without merging