WIP: allow editing of submission by the user
nextcloud/forms pull request #1690
Opened 2023-08-18 10:01 UTC by tpokorra

2023-08-18 11:15 UTC, Chartman123 reviewed
I just added some comments on the Changelog and the translations :)

I didn't have a closer look for now.

But one thing that I already saw: you seem to delete an existing submission instead of updating it. I'm not quite sure if that's the way to go here.

2023-08-18 11:15 UTC, Chartman123 commented on l10n/de.js
Please don't add any translations manually, they will be automatically imported from Transifex. :)

2023-08-18 11:15 UTC, Chartman123 commented on l10n/de.json
Please don't add any translations manually, they will be automatically imported from Transifex. :)

2023-08-18 11:15 UTC, Chartman123 commented on l10n/de_DE.js
Please don't add any translations manually, they will be automatically imported from Transifex. :)

2023-08-18 11:15 UTC, Chartman123 commented on l10n/de_DE.json
Please don't add any translations manually, they will be automatically imported from Transifex. :)

2023-08-18 21:23 UTC, tpokorra commented
Thank you @Chartman123 
I will fix those issues.

The whole pull request is not fully functional yet. 
I still need to get the vue components to display the previously submitted answers.

2023-08-23 10:30 UTC, tpokorra commented
TODO list:
* show checked radio buttons and check boxes with previous answer
* update answer, don't delete and create answer
* allow deletion of answer

2023-08-23 11:15 UTC, Chartman123 commented
@tpokorra I've added your checklist to first post :) And btw thank you very much for your contribution to this project 👍🏻

2023-10-23 15:53 UTC, tpokorra commented
@Chartman123 
I am trying to run the unit tests locally, so that I can fix and extend them.

I have a small question: why is there a reference to `Test\TestCase` in most test files? 

I get this error:

```
tim03-nextcloud@h13:~/nextcloud/apps/forms$ composer test:unit
> phpunit -c tests/phpunit.xml
PHP Fatal error:  Uncaught Error: Class "Test\TestCase" not found in /home/pacs/tim03/users/nextcloud/nextcloud/apps/forms/tests/Unit/Activity/ActivityManagerTest.php:41
Stack trace:
```

If I change it from `Test\TestCase` to `PHPUnit\Framework\TestCase` it just complains about the next file.

Am I missing something to install?

I ran:

```
cd nextcloud/apps/forms
composer install
composer dumpautoload -o
```

phpunit in vendor/bin shows version `9.6.13`

2023-10-23 16:01 UTC, Chartman123 commented
@tpokorra didn't manage to run the unit tests locally...

Regarding the `extends \Test\TestCase` you can also find some information in the dev docs: https://docs.nextcloud.com/server/stable/developer_manual/basics/testing.html

2023-10-23 17:02 UTC, tpokorra commented
@Chartman123 
Thank you, your hint helped.
I needed to copy the folder tests from https://github.com/nextcloud/server/tree/master/tests to my installation of Nextcloud.
I can now fix the test issues.

2024-03-18 21:41 UTC, SergioArbarviro commented
Hello @tpokorra 

I thank you very much for your good work. I fully support this feature, which I believe is very important in many use cases. Do you need help, and if so, where?

2024-10-23 08:04 UTC, Chartman123 commented
@tpokorra are you still working on this feature?

2024-12-31 12:09 UTC, tpokorra commented
I have now a branch for the main branch (Forms 5), and a branch for the branch stable 4.

In this pull request, I will focus on Forms 5.

I will have to go through the tests again, I did not patch them yet.
And then I need to write my own tests for the AllowEdit functionality. 
That has been the big problem in the past, that I do need to learn how the tests are written for Nextcloud.
I will try to focus on that in the coming days.

2025-01-04 10:52 UTC, tpokorra commented
I have dropped the option to delete my own response for now, to keep this PR simpler.
I might create a new PR after this, for adding a delete button. 
At first I thought, in Forms 5 there is the Clear Button, but that is different from a Delete Button.

2025-01-04 11:02 UTC, Chartman123 commented
Yes that's fine for me to break it into smaller pieces.

2025-01-08 07:57 UTC, Chartman123 commented
@tpokorra please don't merge the main branch into this one... always use a `git rebase` for a clean commit history

2025-01-08 09:58 UTC, Chartman123 requested changes
Haven't tested it yet, just a few comments from my first quick look at the code.

2025-01-08 09:58 UTC, Chartman123 commented on lib/Migration/Version030300Date20230815000000.php
> +class Version030300Date20230815000000 extends SimpleMigrationStep {
Please adjust the version number of this migration. It should be a migration for version 5.0.0 and no longer for 3.3.0 ;)

2025-01-08 09:58 UTC, Chartman123 commented on lib/Service/FormsService.php
> +			} catch (DoesNotExistException $e) {
What about the other possible exception `MultipleObjectsReturnedException`?

2025-01-08 09:58 UTC, Chartman123 commented on src/components/SidebarTabs/SettingsSidebarTab.vue
> +					'This can not be controlled, if the form has a public link or stores responses anonymously, or the response can be edited.',
```suggestion
					'This can not be controlled, if the form has a public link, stores responses anonymously, or the response can be edited.',
```

2025-01-08 09:58 UTC, Chartman123 commented on src/components/SidebarTabs/SettingsSidebarTab.vue
> +					'This can not be controlled, if the form has a public link or stores responses anonymously, or multiple responses are allowed.',
```suggestion
					'This can not be controlled, if the form has a public link, stores responses anonymously, or multiple responses are allowed.',
```

2025-01-08 09:58 UTC, Chartman123 commented on src/views/Submit.vue
> +import IconDeleteSvg from '@mdi/svg/svg/delete.svg?raw'
Do you still need this as deleting answers is no longer part of this PR?
```suggestion
```

2025-01-08 09:58 UTC, Chartman123 commented on src/views/Submit.vue
> +			IconDeleteSvg,
Same here
```suggestion
```

2025-01-08 09:58 UTC, Chartman123 commented on lib/Controller/ApiController.php
> +	#[ApiRoute(verb: 'POST', url: Constants::API_BASE . 'forms/{formId}/submissions/{submissionId}', requirements: Constants::API_V3_REQUIREMENTS)]
This should be a PUT request, as we're updating an existing entity.
```suggestion
	#[ApiRoute(verb: 'PUT', url: Constants::API_BASE . 'forms/{formId}/submissions/{submissionId}', requirements: Constants::API_V3_REQUIREMENTS)]
```

2025-01-08 09:58 UTC, Chartman123 commented on lib/Controller/ApiController.php
> +		if ($form->getAllowEdit() && $this->currentUser) {
Shouldn't this be one of the first conditions, so that we don't have to load the questions and validate the updated submissions if editing isn't allowed at all or it's a wrong user?

2025-01-08 09:58 UTC, Chartman123 commented on src/views/Submit.vue
> +					await axios.post(
See comment for ApiController
```suggestion
					await axios.put(
```

2025-01-08 09:58 UTC, Chartman123 commented on tests/Integration/Api/ApiV3Test.php
Update submission test is still missing

2025-01-08 10:28 UTC, Chartman123 commented on lib/Controller/ApiController.php
> +	#[ApiRoute(verb: 'POST', url: Constants::API_BASE . 'forms/{formId}/submissions/{submissionId}', requirements: Constants::API_V3_REQUIREMENTS)]
@provokateurin or would a PATCH be better here?

2025-01-08 10:34 UTC, provokateurin commented on lib/Controller/ApiController.php
> +	#[ApiRoute(verb: 'POST', url: Constants::API_BASE . 'forms/{formId}/submissions/{submissionId}', requirements: Constants::API_V3_REQUIREMENTS)]
HTTP semantics wise PATCH is used for partial updates of a resource and PUT for updating the entire resource.
I don't have much context, but from the looks of the method this updates the entire submission, so PUT seems appropriate.

2025-01-09 19:32 UTC, tpokorra commented on tests/Integration/Api/ApiV3Test.php
You are right. I was not aware of that.
I did a first try, but there is now an issue with uploading a file, which I actually never used yet.
I will have to look into this tomorrow.

2025-01-11 15:49 UTC, Chartman123 commented on tests/Integration/Api/ApiV3Test.php
> +		$uploadedFileResponse = $this->http->request('PUT',
This files need to be POSTed, there's not PUT route available for updating/changing them :)

```suggestion
		$uploadedFileResponse = $this->http->request('POST',
```

2025-01-11 15:50 UTC, Chartman123 commented on tests/Integration/Api/ApiV3Test.php
> +		$uploadedFileResponse = $this->http->request('PUT',
As an alternative you could implement a function to update/change the files on updating the submission. Then the old files should be replaced by the new ones

2025-01-17 08:12 UTC, Chartman123 commented
Hi @tpokorra, do you think you can get this ready by the end of next week? I'd really love to include this into Forms 5.0 which should get a pre-release for the first NC31 RC 👍🏻 

If you need any help just ask :)

2025-01-21 22:11 UTC, tpokorra commented on lib/Service/FormsService.php
> +			} catch (DoesNotExistException $e) {
I am now catching MultipleObjectsReturnedException as well

2025-01-21 23:08 UTC, tpokorra commented
> Hi @tpokorra, do you think you can get this ready by the end of next week? I'd really love to include this into Forms 5.0 which should get a pre-release for the first NC31 RC 👍🏻
> 
> If you need any help just ask :)

I need help.
But I am not sure what to ask for.

At least I got the openapi check fixed.
But it seems the code coverage check now fails again. Not sure what the difference is between codecov/project and codecov/patch. And "View this Pull Request on Codecov" gives an error.

And I don't know why allow_edit is not set in the form in the integration test.

I am happy to give this pull request to someone else, if someone is available and willing.

I think this is a bit above my abilities.

2025-01-21 23:28 UTC, Chartman123 commented
> And I don't know why allow_edit is not set in the form in the integration test.

Are you sure that it's not set? You're condition in here looks a little strange:

https://github.com/SolidCharity/forms/blob/b9e35476f5320954d7ce0c7fefa9a1f2ad4e7f48/lib/Controller/ApiController.php#L1354-L1355

I think you should check if the user who made the submission is the same as the user who wants to update the submission. But there's no comparison on the right side of the `&&`

2025-01-22 10:25 UTC, tpokorra commented
> Edit: or do you just want to check if there is a currently logged in user?

yes, I wanted to check so that there is no null reference later.
Similar to https://github.com/SolidCharity/forms/blob/b9e35476f5320954d7ce0c7fefa9a1f2ad4e7f48/lib/Controller/ApiController.php#L1281
But I have removed the check now

2025-01-22 11:24 UTC, tpokorra commented on tests/Integration/Api/ApiV3Test.php
> +		$uploadedFileResponse = $this->http->request('PUT',
it seems to work now

2025-01-22 11:24 UTC, tpokorra commented on tests/Integration/Api/ApiV3Test.php
the test is now added and working

2025-01-22 11:27 UTC, tpokorra commented
@Chartman123 I think the Pull Request is now in quite a good shape.

2025-01-22 14:31 UTC, Chartman123 commented
@tpokorra thanks for your effort :) I'll have a closer look in the next days! Just one question from looking at the code: how can a user edit his submission? I didn't find any code where the old submission gets loaded into the frontend?

2025-01-22 20:45 UTC, Chartman123 commented
@tpokorra I found it :) 

I'm unsure if we should send the submission with the form itself or if we should move it to an own endpoint `GET /forms/[formId]/submissions?user=[userId]` and then a `GET /forms/[formId]/submissions/[submissionId]`. That way we could also use it if multiple submissions are allowed and show the users a list of their submissions to choose from.

But this can also be a follow-up. We should just agree on how the endpoints should be organised before the release of final Forms 5 so that we won't break the API just shortly after the release.

@susnux what do you think about that?

2025-02-17 02:53 UTC, TUCAOEVER commented
Is there any release date info about this feature?

2025-02-17 06:21 UTC, tpokorra commented
I have no idea why the Playwright Tests are failing.

It seems to fail on 

```
      43 | 	const response = await request.get('apps/files')
    > 44 | 	expect(response.status()).toBe(200)
```

It works in my test installation for me, I can login and see /apps/files

2025-02-17 06:45 UTC, Chartman123 commented
> I have no idea why the Playwright Tests are failing.

You can ignore the failing tests for now. This is because of an dependabot update on the weekend

2025-03-01 16:50 UTC, AIlkiv requested changes
Thank you for your work. A few comments from me.

2025-03-01 16:50 UTC, AIlkiv commented on lib/Controller/ApiController.php
> +		}
if (!empty( $deletingStoredAnswers) {
foreach ( $deletingStoredAnswers as $storedAnswer) {
$this->answerMapper->delete($storedAnswer);
}
}

2025-03-01 16:50 UTC, AIlkiv commented on lib/Service/FormsService.php
> +		if ($this->currentUser->getUID() && $form->getAllowEdit()) {
if this only works for cases where only one submission is allowed. Add !$form->getSubmitMultiple() here

2025-04-21 18:56 UTC, Chartman123 commented
Closed in favor of #2715

2025-04-21 18:56 UTC, closed without merging