Added a new feature: 'Other' option for radio and checkbox questions.
nextcloud/forms pull request #1694
Opened 2023-08-19 16:42 UTC by AIlkiv

I have implemented a feature to provide other answer for radio buttons and checkboxes.

Related to #93

Demo:

![image](https://github.com/nextcloud/forms/assets/5858915/f0b26560-a035-4a8d-ae9f-880dd37a8ef9)

![image](https://github.com/nextcloud/forms/assets/5858915/21b93853-01b1-4bcb-a026-ed0099bd86e3)

![image](https://github.com/nextcloud/forms/assets/5858915/164dc3f5-2478-48c9-aa3a-bed80b831c0a)

2023-08-19 17:59 UTC, Chartman123 commented
Hi @AIlkiv

thanks for contributing :) I'll have a closer look at it in the next few days. In the meantime you could already go on and fix the errors from our check workflows.

@nextcloud/designers what do you think about the implementation? I'd propose to remove the `Other:` label in front of the input field and have it has the placeholder inside the field.

2023-08-20 09:40 UTC, AIlkiv commented
Fixed

2023-08-21 22:43 UTC, Chartman123 requested changes
I had a closer look at your changes and left some comments. :-)

2023-08-21 22:43 UTC, Chartman123 commented on src/components/Questions/QuestionMultiple.vue
> +					{{ t('forms', 'Other:') }}&nbsp;<NcInputField placeholder="answer..." :value.sync="inputOtherAnswer" class="question__input" />
```suggestion
					<NcInputField placeholder={{ t('forms', 'Other...') }} :value.sync="inputOtherAnswer" class="question__input" />
```

Please use the text directly as the placeholder. This is also the way Google handles it in Google Forms.

And please adjust the styling of the Input box to matcht the width of the other question types.

Last, as you also use two different placeholders for view/edit/submit mode, we should just move the placeholder text to AnswerTypes.js like for the other question types.

2023-08-21 22:43 UTC, Chartman123 commented on src/components/Questions/QuestionMultiple.vue
> +						:placeholder="t('forms', 'Field for Other answer')"
See other comment about placeholders

2023-08-21 22:43 UTC, Chartman123 commented on src/components/Questions/QuestionMultiple.vue
> +		isShowOtherAnswer() {
```suggestion
		hasOtherAnswer() {
```

Better wording for method

2023-08-21 22:43 UTC, Chartman123 commented on src/components/Results/ResultsSummary.vue
> +			})
This shows the "Other" option also for dropdown questions.

2023-08-21 22:43 UTC, Chartman123 commented on tests/Unit/Service/SubmissionServiceTest.php
> +			'required-emty-other-answer' => [
```suggestion
			'required-empty-other-answer' => [
```

Typo

2023-08-21 22:43 UTC, Chartman123 commented on tests/Unit/Controller/ApiControllerTest.php
Please only add the test that belong to your PR and add the other tests in a separate PR so that we don't mix several things in one PR.

2023-08-21 23:26 UTC, marcoambrosini commented
Thanks for the contribution @AIlkiv
@Chartman123 we cannot use placeholders to deliver important information because of accessibility problems.

I think that this text field that is shown when other is selected should appear below the radio button and span the whole width of the container.

Also I think it would be nice to see what these "other" results are in the answers page.

2023-08-22 06:18 UTC, Chartman123 commented on src/components/Questions/QuestionMultiple.vue
> +					{{ t('forms', 'Other:') }}&nbsp;<NcInputField placeholder="answer..." :value.sync="inputOtherAnswer" class="question__input" />
> Thanks for the contribution @AIlkiv @Chartman123 we cannot use placeholders to deliver important information because of accessibility problems.
> 
> I think that this text field that is shown when other is selected should appear below the radio button and span the whole width of the container.

@marcoambrosini Thanks for your input 🙂 

Here are two screenshots how Google handles it currently:

|Edit|View|
|---|---|
|![image](https://github.com/nextcloud/forms/assets/16020496/1e1e8c67-bcd9-42f8-a114-bb454ab3e992)|![image](https://github.com/nextcloud/forms/assets/16020496/82f63b92-196e-4b13-94fb-69e9483ee549)|

So it's a combination of what I suggested and @AIlkiv implemented. As they don't have a border around the input box it looks fine with the input box in line with the radio/checkbox button.

How would Allkiv's version look like with a RTL language?

2023-08-22 06:21 UTC, Chartman123 commented
> Also I think it would be nice to see what these "other" results are in the answers page.

@marcoambrosini This could blow up the results even for the "same" answers if they are typed differently, but I also thought about this...

2023-08-22 07:13 UTC, marcoambrosini commented
> @marcoambrosini This could blow up the results even for the "same" answers if they are typed differently, but I also thought about this...

Maybe we could think about a way to "dive" into answers within the "others" bucket?

2023-08-22 13:46 UTC, AIlkiv commented
> Also I think it would be nice to see what these "other" results are in the answers page.

@marcoambrosini You can see the value of 'Other' in the Responses section.

2023-08-23 06:35 UTC, AIlkiv commented on src/components/Questions/QuestionMultiple.vue
> +					{{ t('forms', 'Other:') }}&nbsp;<NcInputField placeholder="answer..." :value.sync="inputOtherAnswer" class="question__input" />
> Please use the text directly as the placeholder. This is also the way Google handles it in Google Forms.
> 
> And please adjust the styling of the Input box to match the width of the other question types.
> 
> Last, as you also use two different placeholders for view/edit/submit mode, we should just move the placeholder text to AnswerTypes.js like for the other question types.
@Chartman123 

![image](https://github.com/nextcloud/forms/assets/5858915/16bc2a3d-a8a8-44a1-bc04-2e9b59fb3e05)

![image](https://github.com/nextcloud/forms/assets/5858915/7292347e-d398-4e4b-a08a-88b0083fe5c5)

![image](https://github.com/nextcloud/forms/assets/5858915/2404163f-45ce-4e4a-af05-c63d9519524c)

> How would Allkiv's version look like with a RTL language?

![image](https://github.com/nextcloud/forms/assets/5858915/50fe703d-4a66-47e3-bd36-695e4aff640c)

When editing, the layout of some fields is displayed incorrectly, but this is the topic of a separate task:

![image](https://github.com/nextcloud/forms/assets/5858915/f6b6991c-edbe-4bf4-bff7-4ef47248ea73)

2023-08-23 06:44 UTC, AIlkiv commented
@Chartman123  It looks like I fixed everything.

2023-08-23 07:41 UTC, marcoambrosini commented
@nextcloud/designers what do you think about this? I think it's still best to keep the input field below the radio. 
Looks better and works better on mobile screens.

2023-08-23 08:01 UTC, Chartman123 commented on src/components/Questions/QuestionMultiple.vue
> +					{{ t('forms', 'Other:') }}&nbsp;<NcInputField placeholder="answer..." :value.sync="inputOtherAnswer" class="question__input" />
> When editing, the layout of some fields is displayed incorrectly, but this is the topic of a separate task:

Yes, there's already another PR open to improve RTL support :)

2023-08-23 10:57 UTC, nimishavijay commented
Very cool! I don't have a strong opinion on the placement of the field, we can show it below like @marcoambrosini said so that it's nicely left aligned with the rest of the options :) 

Rest of design looks great, some wording suggestions
- [ ] "People can enter a other answer" --> "People can submit a different answer" 
- [ ] "Enter your other answer" --> "Enter your answer" (to avoid duplication of the word "Other")
- [ ] "Other..." --> "Other" (we usually use ellipses when there is some text that is cut off or hidden)

2023-08-23 21:00 UTC, Chartman123 commented
Two more things: 
- First, I think that we should make sure, that if "other" is selected as answer, the input field should have a value. Currently you can select it but don't have to enter a value. Google allows this, too, but I don't think that this makes sense.
- I just saw that the hover effect doesn't look good with the text field, for both the in-line version and the new-line version. But I'm not sure what would be the best way to deal with it.

@marcoambrosini If we just add the line break like in the screenshots above, I don't like the look as it moves the text higher than the checkbox next to it. So did you think of a completely new line with the left alignment like for a normal input field? In this case we could also limit the hover effect to just the checkbox and the "Other: " label.

However, I don't think it's too problematic on mobile screens with the in-line field: (compared to the short answer field below)
![grafik](https://github.com/nextcloud/forms/assets/16020496/40da42ae-e0d2-4c30-a930-52116f637627)

2023-08-23 21:32 UTC, Chartman123 commented on src/components/Questions/QuestionMultiple.vue
> +						:maxlength="maxStringLengths.optionText"
Don't we have to add the string length of the prefix to the length of the input field for storing the value in the database? So we need to make sure the input is only maxStringLenghts.optionText (1024) - QUESTION_EXTRASETTINGS_OTHER_PREFIX.length() (20) = 1004

However, this is the wrong place to check this, as this is only used for the edit mode, where we can't add any text to the input field. So you have to move this maxlenght limitation to the input field in view mode.

2023-08-23 22:36 UTC, marcoambrosini reviewed
Regardless of the positioning of the text field, it shouldn't be within the radio button's bundaries. If we do it inline we need to make sure it wraps on mobile screens

<img width="610" alt="Screenshot 2023-08-24 at 07 35 46" src="https://github.com/nextcloud/forms/assets/26852655/cb7be5d9-61b5-4eec-9856-a3ca55c96c1f">

2023-08-24 05:36 UTC, AIlkiv commented
> Незалежно від розташування текстового поля, воно не повинно бути в межах перемикача. Якщо ми робимо це вбудовано, нам потрібно переконатися, що воно переносить екрани мобільних пристроїв

@marcoambrosini In this version, in my opinion, there is no understanding that the radio button and the input field are one field.

In Google Forms on mobile devices, it looks normal when everything is in one row.

2023-08-24 06:14 UTC, marcoambrosini commented
Google Forms' layout breaks on a mobile screen though.
 
<img width="264" alt="Screenshot 2023-08-24 at 15 13 11" src="https://github.com/nextcloud/forms/assets/26852655/d21facca-a49e-42db-bf49-5b620eacf53c">

2023-08-25 05:41 UTC, AIlkiv commented
> Regardless of the positioning of the text field, it shouldn't be within the radio button's boundaries. If we do it inline we need to make sure it wraps on mobile screens
> 
> <img alt="Скріншот 2023-08-24 на 07 35 46" width="610" src="https://user-images.githubusercontent.com/26852655/262814630-cb7be5d9-61b5-4eec-9856-a3ca55c96c1f.png">

@marcoambrosini  Your example has an additional label, making it appear well-structured. I attempted to break it into two lines, but it seems less intuitive to me (I see four options and a separate option to enter an answer). What are your thoughts?

![image](https://github.com/nextcloud/forms/assets/5858915/dd6456a2-e6cd-4bb3-8232-36f5cac5de13)

![image](https://github.com/nextcloud/forms/assets/5858915/252f9efd-7eaf-4187-a4f4-6eb6e196eb50)

2023-08-25 06:37 UTC, Chartman123 commented
@AIlkiv could you try to align the text inside the input field with the text of the other options? And to make it more clear that they both belong together you could change the label to `Other:` again

2023-08-25 06:48 UTC, AIlkiv commented
> @AIlkiv could you try to align the text inside the input field with the text of the other options? And to make it more clear that they both belong together you could change the label to `Other:` again

@Chartman123 

![image](https://github.com/nextcloud/forms/assets/5858915/4b907451-dcea-4e1a-86cd-38fcd7c85905)

![image](https://github.com/nextcloud/forms/assets/5858915/9f2e23b7-959b-4c1a-b07a-f3251bc549b1)

![image](https://github.com/nextcloud/forms/assets/5858915/1ad05cb8-50be-4360-aa4e-7c90f15f37ec)

2023-08-25 07:01 UTC, Chartman123 commented
@marcoambrosini ok, you're right. 👍🏻 

@AIlkiv you can use `v-if="isMobile"` here

2023-08-25 07:10 UTC, marcoambrosini commented
> you can use v-if="isMobile" here

@Chartman123  I don't think we can use `isMobile` here. `isMobile` just tells us that the total width of the page is below `1024px`, in which the inline input would still look fine.
Conversely, we might have a 4k widescreen but have this form placed in a tiny area of the page or in a dialog. 

So what we really care about is the width of the container, but that's a bit hard to "watch". I suggest we put the button and input in a flexbox and give a `min-width` of `300px` to the input with `flex-wrap` set to `wrap`

2023-08-25 11:22 UTC, AIlkiv commented
![image](https://github.com/nextcloud/forms/assets/5858915/4c4c3631-cd1b-4a9b-beb4-c17117bf9abb)

![image](https://github.com/nextcloud/forms/assets/5858915/a6c69799-2e5c-46b5-be37-620e78aed4a8)

![image](https://github.com/nextcloud/forms/assets/5858915/0e923635-b1ff-4487-8258-39a62464edb9)

@Chartman123 @marcoambrosini Is it normal?

In order to prevent the "hover" effect from overlapping the input field, I had to add a margin after the label "Other:"

2023-08-25 17:34 UTC, AIlkiv commented on src/components/Questions/QuestionMultiple.vue
> +						:maxlength="maxStringLengths.optionText"
We only store values in the database.

2023-08-25 18:36 UTC, AIlkiv commented
@Chartman123 Fixed everything.

2023-08-25 21:12 UTC, Chartman123 commented on src/components/Questions/QuestionMultiple.vue
> +						:maxlength="maxStringLengths.optionText"
My bad... sorry, you're of course correct :)

2023-08-25 21:25 UTC, Chartman123 commented
@AIlkiv looks good from my side 👍🏻  just one last thing: you could shorten your commit message to `feat: ...` if you want to :)

2023-08-25 21:43 UTC, Chartman123 approved these changes

2023-08-26 07:33 UTC, susnux commented on lib/Service/SubmissionService.php
> +				(!$questionAnswered || !array_filter($answers[$questionId], 'strlen') || !array_filter($answers[$questionId], fn ($value) => $value !== Constants::QUESTION_EXTRASETTINGS_OTHER_PREFIX))) {
Not sure if we want to limit the new check to `in_array($question['type'], Constants::ANSWER_TYPES_PREDEFINED))`.
Otherwise also text input fails if it includes that string. (should not happen, but why not?)

2023-08-26 07:35 UTC, susnux approved these changes
Very nice! Thank you :tada: 

Looks good overall, I do not like the `otherAnswer` name, but should be ok.
So, this good from my point :)

2023-08-26 08:03 UTC, Chartman123 commented on lib/Service/SubmissionService.php
> +				(!$questionAnswered || !array_filter($answers[$questionId], 'strlen') || !array_filter($answers[$questionId], fn ($value) => $value !== Constants::QUESTION_EXTRASETTINGS_OTHER_PREFIX))) {
Yes, makes sense in my opinion 👍🏻

2023-08-26 08:07 UTC, Chartman123 commented
> I do not like the otherAnswer name

Do you have something better in mind? We could still change it before merging...

2023-08-26 12:53 UTC, susnux commented
> Do you have something better in mind? We could still change it before merging...

Not really, I just think it is a bit misleading. It sounds like it is possible to have multiple different answers.
Maybe like `isRequired` we could use `allowCustomAnswer`?

2023-08-27 09:25 UTC, Chartman123 commented
@AIlkiv Before merging, could you please add the new prop to the docs at docs/API.md and docs/DataStrutcture.md?

2023-08-27 11:11 UTC, AIlkiv commented on lib/Service/SubmissionService.php
> +				(!$questionAnswered || !array_filter($answers[$questionId], 'strlen') || !array_filter($answers[$questionId], fn ($value) => $value !== Constants::QUESTION_EXTRASETTINGS_OTHER_PREFIX))) {
Add `!empty($question['extraSettings']->allowedOtherAnswer)`

2023-08-27 11:16 UTC, AIlkiv commented
> Maybe like `isRequired` we could use `allowCustomAnswer`?

I modified the name to 'allowOtherAnswer' in the 'extraSettings'.

2023-08-27 11:32 UTC, susnux commented
> > Maybe like `isRequired` we could use `allowCustomAnswer`?
> 
> I modified the name to 'allowOtherAnswer' in the 'extraSettings'.

Nice, please push the changes and add it to the api docs, then we can merge this :)

2023-08-27 13:02 UTC, AIlkiv commented
@Chartman123 @susnux Finished

2023-08-27 13:45 UTC, Chartman123 approved these changes

2023-08-27 21:42 UTC, susnux commented on src/components/Questions/QuestionMultiple.vue
> +.question__other-answer::v-deep {
Is the deep sector required? If yes we should use `:deep()` as v-deep id deprecated

2023-08-28 01:08 UTC, marcoambrosini commented
> I had to add a margin after the label "Other:"

@AIlkiv could you add a bigger margin, say 8px?

2023-08-28 19:28 UTC, AIlkiv commented on src/components/Questions/QuestionMultiple.vue
> +.question__other-answer::v-deep {
This is required for a single selector. Divided into parts with :deep() and without :deep().

2023-08-28 19:29 UTC, AIlkiv commented
> @AIlkiv could you add a bigger margin, say 8px?

@marcoambrosini  Changed code and push

![image](https://github.com/nextcloud/forms/assets/5858915/1e423628-e6a0-4359-9573-f8fdf49f326d)

2023-08-29 05:53 UTC, AIlkiv commented
> Sorry @AIlkiv, without the checked feedback the input field looks too far from the label "Other", so could we dial back the margin to 4px. Thank you :)

Ok, refreshed commit.

![image](https://github.com/nextcloud/forms/assets/5858915/c74a04ce-dd7f-4413-bdfc-c4d5c8a88f22)

2023-08-29 07:40 UTC, marcoambrosini commented
Thanks a lot for your contributions @AIlkiv and @Chartman123 ❤️

2023-08-29 07:40 UTC, merged

2023-08-29 08:11 UTC, AIlkiv commented
@marcoambrosini @Chartman123 @susnux  Thank you for the collaboration!