enh: Add forms `state` to close and archive forms
nextcloud/forms pull request #1925
Opened 2024-01-30 11:18 UTC by susnux

TBD

2024-02-18 16:55 UTC, susnux commented
Rebased, squashed and fixed the tests. Ready for review :)

2024-02-18 17:19 UTC, susnux commented
Only the codecov actions fails... see the PR for updating it...

Meaning that is unrelated.

2024-02-18 18:36 UTC, Chartman123 commented
> Only the codecov actions fails... see the PR for updating it...

But the error here is just an invalid token. I experimented with the token yesterday. Perhaps we just need to paste it once more into the repository secrets.

The other PR is about stable3.

Also please add the new prop to the docs :)

2024-02-18 18:55 UTC, susnux commented
> Also please add the new prop to the docs :)

@Chartman123 already done :)

2024-02-18 23:03 UTC, Chartman123 reviewed
Found a few typos. Rest seems fine :) We should ask the designers about their opinion. IIRC Jan didn't want to have the archived forms in the App Navigation but in a modal...

2024-02-19 12:47 UTC, susnux commented on lib/Migration/Version040100Date20240218201500.php
> +<?php
Yes, need to update here :)

2024-02-19 12:59 UTC, susnux commented
> We should ask the designers about their opinion. IIRC Jan didn't want to have the archived forms in the App Navigation but in a modal...

I have added screenshots and requested a review from @jancborchardt :)

2024-02-19 15:11 UTC, jancborchardt reviewed
Yeah, "Archived forms" would be better as a sticky entry on the bottom left which opens a modal, just like in Contacts and Calendar.

2024-02-19 20:35 UTC, susnux commented on lib/Migration/Version040100Date20240218201500.php
> +<?php
renamed

2024-02-19 20:37 UTC, susnux commented
> Yeah, "Archived forms" would be better as a sticky entry on the bottom left which opens a modal, just like in Contacts and Calendar.

Thank you @jancborchardt !
I now changed it to show the archived forms in a dialog / modal instead:


https://github.com/nextcloud/forms/assets/1855448/81451fa8-c5da-4669-b521-64004d5deea5

2024-02-19 22:19 UTC, Chartman123 commented
One more thing: Do you really want to move closed/expired forms into a separate area in the App Navigation? I think this is not necessary as we already have the archiving for hiding them from the list and the subtitle for the closed/expired forms to identify them directly. 

Think of a freshly expired form: if you have a large list of forms, you would have to scroll first to see the latest results.

2024-02-20 10:00 UTC, Chartman123 commented
Yes I understand that and agree that after a while they will be less important. But for that one can archive the form. So I'd be happier without this grouping :)

2024-02-22 15:34 UTC, Chartman123 reviewed
I found a problem with the migration...

2024-02-26 14:12 UTC, susnux commented on lib/Migration/Version040200Date20240219201500.php
> +			->executeStatement();
Fixed

2024-02-26 23:10 UTC, Chartman123 approved these changes
Looks good now :)

Just some design/UX related things: Should we make it possible to dearchive a form directly from the modal? And on a public share page you always show the "expired" message in the NcEmptyContent as the FormsService always returns isExpired as soon as the state is not "active". So no hint for archived/closed there...

2024-02-26 23:15 UTC, Chartman123 commented
One more comment: the `state` is not imported in `FormsMigrator.php`. The linked file related props are also missing, but I'm not sure if they really make sense when you import a Form in another instance. The state however could make sense, so I think we should add it there.

2024-03-06 18:48 UTC, Chartman123 commented
Please integrate the fix for #1991 into this PR. Should be easy to fix and you can directly address the new state prop as well :)

2024-03-07 10:18 UTC, jancborchardt requested changes
Sorry for the late design feedback, 3 things:
- [x] The layout of the left navigation is a bit off, lot of whitespace (e.g. below the "Your forms" heading) and the entries are too big. Since there is no subline, they should be single-line entries like in Files or the left navigation of Mail, not multiline list items like in Talk or the message list in Mail.
- [ ] The "Archived forms" entry on the bottom does not have proper spacing to the bottom. Check how "Files settings" does it – left aligned, tertiary button, non-bold text.
- [x] In the modal, the actions button should show for all entries by default, not only on hover or focus → this is better for discoverability

2024-03-20 00:32 UTC, susnux commented
Thank you for the feedback, I resolved the comments :)


https://github.com/nextcloud/forms/assets/1855448/17aa10b9-57ee-49e9-9747-594226924215

2024-03-20 18:23 UTC, Chartman123 commented on lib/Controller/ApiController.php
> +		$forms = $this->formMapper->findActiveForms();
I think we always need to process all form here... If you only look for the active forms, a user with `results` permission can't see an expired/inactive/archived form in the sidebar. So basically this reverts my bugfix ;)

2024-03-20 23:32 UTC, Chartman123 commented on lib/Controller/ApiController.php
> +		$forms = $this->formMapper->findActiveForms();
I pushed a fix, please double check 😇

2024-03-21 18:09 UTC, Chartman123 commented on lib/Controller/ApiController.php
> +		$forms = $this->formMapper->findActiveForms();
I forgot to remove the findActiveForms method, just added this to my commit as this method isn't used anywhere else

2024-03-22 09:39 UTC, susnux reviewed
@Chartman123 changes make sense, one comment.

But I think we need a follow up some when, because always loading all forms is pretty bad. For small instances this works but what if there are 30'000 forms? 100'000?

2024-03-22 10:45 UTC, Chartman123 commented on src/components/AppNavigationForm.vue
> +			<NcActionButton v-if="canEdit && !isArchived" :close-after-click="true" @click="onCloneForm">
Because it didn't work in the first place... I tried to click the button, but nothing happened. It only works from the Navigation sidebar. That's why I hid the button in the modal. Can also be a follow-up PR :)

2024-03-22 10:58 UTC, susnux commented on src/components/AppNavigationForm.vue
> +			<NcActionButton v-if="canEdit && !isArchived" :close-after-click="true" @click="onCloneForm">
:+1:

2024-03-22 12:34 UTC, susnux commented
Should be ready to merge now

2024-03-22 16:29 UTC, Chartman123 approved these changes

2024-03-22 16:31 UTC, merged