feat: Allow to reorder options of "checkbox" "radio" and "dropdown" question types
nextcloud/forms pull request #2092
Opened 2024-04-22 10:59 UTC by susnux

* Resolves https://github.com/nextcloud/forms/issues/354

This adds support to reorder options instead of having to remove them.
It works but I had to modify a lot of places to keep smooth behavior of the list ordering.

Implementation things:
* I am not sure about the API endpoint, it does not match our current naming style
* Should we expose the "order" property or just keep it internally and only return options sorted?

@nextcloud/designers question:
* There is not much space for a "drag" handle + a11y button so I just used buttons, I do not think it looks super awesome, but it works. Do you have an idea how to improve? Especially because there is already the drag handle for the question itself.

## Screenshots

Shuffle options enabled = no sorting | No shuffle = you can sort
---|---
![Screenshot 2024-04-22 at 12-31-10 fff9 - Forms - Nextcloud](https://github.com/nextcloud/forms/assets/1855448/a356c2de-a62c-47a8-b699-cf993f785f3a)|![Screenshot 2024-04-22 at 12-31-51 fff9 - Forms - Nextcloud](https://github.com/nextcloud/forms/assets/1855448/c4f199a0-15f8-490c-8029-cd2bf98780af)

2024-04-22 11:17 UTC, szaimen commented on src/components/Questions/AnswerInput.vue
> +						<IconClose :size="20" />
I think this should rather use a delete icon instead of a close icon?

2024-04-22 11:17 UTC, szaimen commented
> * There is not much space for a "drag" handle + a11y button so I just used buttons, I do not think it looks super awesome, but it works. Do you have an idea how to improve? Especially because there is already the drag handle for the question itself.

I think it looks fine but had some suggestion :)

2024-04-22 11:42 UTC, Chartman123 reviewed
Some things I found by looking at the code, did not test it by now.

2024-04-22 11:42 UTC, Chartman123 commented on appinfo/routes.php
> +				'apiVersion' => 'v2(\.5)?'
I'd switch those two lines. Makes more sense alphabetically and also based on the appearance in the URL
```suggestion
				'apiVersion' => 'v2(\.5)?',
				'id' => '\d+'
```

2024-04-22 11:42 UTC, Chartman123 commented on docs/API.md
> +- In API version 2.5 the endpoint `/api/v2.5/options` was added for `PATCH` requests to reorder options
Doesn't fit to the defined route.

2024-04-22 11:42 UTC, Chartman123 commented on lib/Controller/ApiController.php
> +	 * @param int[] Order to use
```suggestion
	 * @param int[] $order Order to use
```
Parameter name was missing

2024-04-22 11:42 UTC, Chartman123 commented on src/components/Questions/AnswerInput.vue
> +			return t('forms', 'An answer for the {index} option', { index: this.index + 1 })
```suggestion
			return t('forms', 'An answer for the option {index}', { index: this.index + 1 })
```
Wouldn't this result in "An answer for 1 option" which should be "1st option"?

2024-04-22 12:32 UTC, susnux commented on src/components/Questions/AnswerInput.vue
> +			return t('forms', 'An answer for the {index} option', { index: this.index + 1 })
Basically copied / moved from here:
https://github.com/nextcloud/forms/pull/2092/files#diff-644e72f1327ea20409e3f75541d13240c8d29e59ddfdfd14e3c261d3df3ca7d1L7

But yes looks weird

2024-04-22 12:49 UTC, susnux commented on docs/API.md
> +- In API version 2.5 the endpoint `/api/v2.5/options` was added for `PATCH` requests to reorder options
This was my first idea, see commit in initial post. I am not sure if the current fits best?

2024-04-22 14:36 UTC, jancborchardt reviewed
> There is not much space for a "drag" handle + a11y button so I just used buttons, I do not think it looks super awesome, but it works. Do you have an idea how to improve? Especially because there is already the drag handle for the question itself.

@susnux what about using a drag handle that on click/enter shows a menu saying "Move up" and "Move down"? Then it would be 1 icon less, and both cases would be covered.

Questions:
- Should the drag handle be on left or right – I would tend towards left
- Which icon to use. I’d say the simple "drag" – or we use that for the whole question, and the "drag-horizontal-variant" for the individual replies?

2024-04-22 14:54 UTC, Chartman123 commented
> drag handle that on click/enter shows a menu saying "Move up" and "Move down"

@jancborchardt This would on the other hand introduce one more click for every move operation...

> * Should the drag handle be on left or right – I would tend towards left

having the handle on the left would introduce one more difference between edit and view mode, but we already have some differences, so I'd be fine with that. Whatever looks better as a whole.

2024-04-23 08:19 UTC, susnux commented
The problem with a drag handle on the left is the conflict with the drag handle for the question itself.
We would then have two drag handles next to each other. Not sure about that.

2024-08-09 10:26 UTC, Chartman123 commented
@susnux @jancborchardt What about having the arrow icons as an overlay at the end of the input fields that only shows up when the field has the focus / hover?

@susnux should I add your backend code to the API v3 PR or would you like to keep it in here and adjust it after v3 merge?

2024-08-11 14:39 UTC, susnux commented
> adjust it after v3 merge?

will adjust afterwards :)

2024-08-26 14:14 UTC, jancborchardt reviewed
> What about having the arrow icons as an overlay at the end of the input fields that only shows up when the field has the focus / hover?

@Chartman123 sounds good! Then it’s not that much visual noise, and the fields are nicely aligned in width. :)

2025-02-16 18:38 UTC, Chartman123 commented
This is now rebased to our current main. Design-wise there's still some room for improvement as I'm really no expert in CSS stuff. But I already made the arrows overlay the input fields.

@jancborchardt what do you think?

![grafik](https://github.com/user-attachments/assets/8b96ca83-7c95-449a-a1e1-2b74c760c884)

2025-02-17 13:27 UTC, marcoambrosini commented
@Chartman123 @jancborchardt is out on vacation and I'm replacing him. 
The arrows look good! Please make sure that their respective buttons are of `--clickable-area` size and that the icons are centered in them. Since these are tertiary buttons we don't need any extra margins. 
One question: shouldn't the arrows show only when the input field is focused? 

Other than that, for the left drag handle I would suggest this icon:
https://fonts.google.com/icons?selected=Material+Symbols+Outlined:drag_indicator:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=drag&icon.size=24&icon.color=%23e8eaed
<img width="173" alt="Screenshot 2025-02-17 at 14 25 34" src="https://github.com/user-attachments/assets/2207374b-20cf-45e2-8d5f-dda8839313fd" />

2025-02-17 14:08 UTC, Chartman123 commented
> One question: shouldn't the arrows show only when the input field is focused?

@marcoambrosini yes, but this might perhaps also be an a11y issue? and we can also deliver it in one of the next minor/patch releases :)

> The arrows look good! Please make sure that their respective buttons are of `--clickable-area` size and that the icons are centered in them. Since these are tertiary buttons we don't need any extra margins.

Is the size not managed directly by using the `NCButton`?

2025-02-17 16:40 UTC, Chartman123 commented
@marcoambrosini so instead of the arrows on the right a drag handle (also on the right) and the up/down actions behind the action menu?

2025-02-17 17:17 UTC, marcoambrosini commented
Yes exactly

2025-02-20 08:25 UTC, AIlkiv requested changes

2025-02-20 08:25 UTC, AIlkiv commented on src/mixins/QuestionMultipleMixin.ts
> +			if (index > 0) {
There is no need for this if, because the button that calls this logic will be disable when index = 0

2025-02-20 08:25 UTC, AIlkiv commented on src/mixins/QuestionMultipleMixin.ts
> +			if (index === this.sortedOptions.length - 1) {
There is no need for this if, because the button that calls this logic will be disable when index = this.sortedOptions.length - 1

2025-02-20 08:25 UTC, AIlkiv commented on src/components/Questions/AnswerInput.vue
> +		 * Handle compostion start event for IME inputs
compostion > composition

2025-02-20 08:25 UTC, AIlkiv commented on src/components/Questions/AnswerInput.vue
> +		 * Handle compostion end event for IME inputs
compostion > composition

2025-02-20 08:30 UTC, AIlkiv commented
I don't think you should overlap the input borders on hover. I tested on version 30.

![image](https://github.com/user-attachments/assets/a9985619-9dbd-4eaf-889f-bbaf24b3a6d3)

2025-02-20 16:02 UTC, Chartman123 commented
@max-nextcloud any idea why the e2e tests are failing without my changes? I mean we're still using aria-labels, even if they are now coming from a computed prop: https://github.com/nextcloud/forms/pull/2092/commits/acfe0a3f2dd4af19e8b5c4fd7fbba4b7f2b31675

2025-02-23 13:41 UTC, susnux commented
> Yes this has to be fixed, but not a blocker as the buttons will also be replaced in #2579 by a drag handle

But we still need buttons in addition so it can be moved with keyboard only

2025-02-23 13:41 UTC, susnux commented on src/mixins/QuestionMultipleMixin.ts
> +			if (index > 0) {
still makes sense for this method to be defensive and not rely on template conditions

2025-02-23 13:41 UTC, susnux commented on src/mixins/QuestionMultipleMixin.ts
> +			if (index === this.sortedOptions.length - 1) {
still makes sense for this method to be defensive and not rely on template conditions

2025-02-23 13:45 UTC, Chartman123 commented
> > Yes this has to be fixed, but not a blocker as the buttons will also be replaced in #2579 by a drag handle
> 
> But we still need buttons in addition so it can be moved with keyboard only

Sure, they are preserved and with better styling in the linked follow up PR

2025-02-23 15:01 UTC, susnux commented
> I don't think you should overlap the input borders on hover. I tested on version 30.

Resolved

2025-02-23 19:49 UTC, Chartman123 approved these changes

2025-02-23 19:52 UTC, Chartman123 commented
Failing workflow unrelated (see fix in #2592)

2025-02-23 19:53 UTC, merged