Add QR-Code for Share Links
nextcloud/forms pull request #2162
Opened 2024-05-11 19:00 UTC by Himmelxd

Closes #1606
at least supposed to
![image](https://github.com/nextcloud/forms/assets/35049588/f2214430-f002-46a9-be46-e14356ed43bf)

2024-05-12 08:28 UTC, Chartman123 commented on src/components/QrModal.vue
> +  - @author René Gieling <github@dartcafe.de>
Please adjust the copyright

2024-05-12 08:28 UTC, Chartman123 commented on l10n/de.json
> +    "Show QR-Code" : "QR-Code anzeigen",
Please remove this change, will be added automatically from Transifex

2024-05-12 08:28 UTC, Chartman123 commented on l10n/de_DE.json
> +    "Show QR-Code" : "QR-Code anzeigen",
Please remove this change, will be added automatically from Transifex

2024-05-12 08:28 UTC, Chartman123 commented on src/components/QrModal.vue
> +<!--
Why don't you use a plain NcModal instead of this custom modal here?

2024-05-12 08:28 UTC, Chartman123 commented on src/components/SidebarTabs/SharingSidebarTab.vue
> +  <template>
Too many spaces

2024-05-12 08:28 UTC, Chartman123 commented on src/components/SidebarTabs/SharingSidebarTab.vue
> +import { NcModal } from '@nextcloud/vue'
Please use the same syntax as for the other imports from the nextcloud-vue lib

2024-05-12 08:29 UTC, Chartman123 commented
@Himmelxd thanks for this PR :) I added some comments on the code

2024-05-12 19:10 UTC, Chartman123 reviewed
Some more comments and in my opinion improvements. @susnux Please also have a look at it 🙂

2024-05-12 21:55 UTC, Himmelxd commented on src/components/SidebarTabs/SharingSidebarTab.vue
> +				</p>
Great Idea, sadly this makes it worse for long liks. Since if it is disabled you cant even scroll over the ... (on clicking).
If not disabled (and resetting on input) it is still close to always not fully displayed, but than you could at least scroll through the link.
![image](https://github.com/nextcloud/forms/assets/35049588/8344b6ff-4ec1-41e2-b352-e3cf1db3e708)

2024-05-12 22:34 UTC, Chartman123 commented on src/components/SidebarTabs/SharingSidebarTab.vue
> +				</p>
You can select and copy the whole link for example by triple clicking on the field. I was also able to select the text with the mouse by clicking and dragging the cursor to the right, but yes it's suboptimal... We could also leave the textual representation away, as there's already the existing button to copy the link to the clipboard.

2024-05-12 22:57 UTC, Himmelxd commented on src/components/SidebarTabs/SharingSidebarTab.vue
> +				</p>
Not really a fan of unlabeled qr-codes, but there is enough context through the title i guess. 
Since copying is not the goal i opt for leaving the full link.

2024-05-13 06:39 UTC, Chartman123 commented on src/components/SidebarTabs/SharingSidebarTab.vue
> +					<NcActionButton @click.prevent="openQrModal(getPublicShareLink(share))">
With the ActionButton you can use the @click event and don't have to prevent the default action.
```suggestion
					<NcActionButton @click="openQrModal(getPublicShareLink(share))">
```

2024-05-13 06:39 UTC, Chartman123 commented on src/components/SidebarTabs/SharingSidebarTab.vue
> +}
```suggestion
}
```
The empty line is still there... ;)

2024-05-13 06:39 UTC, Chartman123 commented on src/components/SidebarTabs/SharingSidebarTab.vue
> +			}
```suggestion
			},
```
Missing trailling comma to silence the lint warning

2024-05-13 06:44 UTC, Chartman123 commented on src/components/SidebarTabs/SharingSidebarTab.vue
> +				</p>
To still have it viewable you could add the qrmodal.text to the `title` attribute of the img. And for the `alt` attribute we should perhaps use something like "QR code representation of ..." for a11y reasons?

2024-05-13 07:44 UTC, Chartman123 commented on src/components/SidebarTabs/SharingSidebarTab.vue
> +						{{ t('forms', 'Show QR-Code') }}
```suggestion
						{{ t('forms', 'Show QR code') }}
```
In English it's without the hyphen and a lowercase 'c'

2024-05-13 08:51 UTC, Himmelxd commented on src/components/SidebarTabs/SharingSidebarTab.vue
> +				</p>
sounds and look good 👍

2024-05-13 08:57 UTC, Chartman123 commented on src/components/SidebarTabs/SharingSidebarTab.vue
> +					<img :src="qrModal.uri" :title="qrModal.text" :alt=" t('forms', 'QR code representation of') + ' ' + form.title ">
`t()` supports parameters directly. That way the translators can move the parameter to where they need in the different languages.

See here: https://github.com/nextcloud/forms/blob/2c7f4a83a6613c7e82e90f1b66b58b5fbdf4e1b4/src/views/Submit.vue#L37

2024-05-13 09:02 UTC, Himmelxd commented on src/components/SidebarTabs/SharingSidebarTab.vue
> +					<img :src="qrModal.uri" :title="qrModal.text" :alt=" t('forms', 'QR code representation of') + ' ' + form.title ">
thats smart

2024-05-13 09:44 UTC, Chartman123 reviewed
So except those two comments (that slipped through before), everything looks fine from my side. Could you please squash all commits into one?

2024-05-13 09:44 UTC, Chartman123 commented on src/components/SidebarTabs/SharingSidebarTab.vue
> +import IconQr from 'vue-material-design-icons/Qrcode.vue'
Oh, I missed that one... please also fix the ordering here :)

2024-05-13 09:44 UTC, Chartman123 commented on src/components/SidebarTabs/SharingSidebarTab.vue
> +		IconQr,
Same here

2024-05-13 13:10 UTC, Chartman123 approved these changes
Fine for me now :) @susnux please have another look

2024-05-13 15:32 UTC, Himmelxd commented
Thank you for your review and great comments :D

2024-05-16 10:27 UTC, susnux commented on src/components/SidebarTabs/SharingSidebarTab.vue
> +		<NcModal v-if="qrModal.on" size="small" @close="qrModal.on=false">
Please use NcDialog instead for this

2024-05-16 10:31 UTC, susnux commented on src/components/SidebarTabs/SharingSidebarTab.vue
> +				<h2>{{ form.title }}</h2>
Maybe *Share {form title}* ?

2024-05-16 10:37 UTC, susnux commented on src/components/SidebarTabs/SharingSidebarTab.vue
> +			},
I am not sure about this, I would prefer having a `QRCodeDialog` component to split up the code a bit.
Then we only need a `showQRCodeDialog: boolean` data pass the public share link to the component.

If we really want to keep it here, then I still we do not need those data attributes. As only the "show qr code" is a real reactive data, text an uri are calculated values.

2024-05-16 11:02 UTC, Chartman123 commented on src/components/SidebarTabs/SharingSidebarTab.vue
> +		<NcModal v-if="qrModal.on" size="small" @close="qrModal.on=false">
Oh, my bad... I suggested to use NcModal

2024-05-16 12:13 UTC, Himmelxd commented on src/components/SidebarTabs/SharingSidebarTab.vue
> +				<h2>{{ form.title }}</h2>
can you please elaborate on that 😅

2024-05-16 12:35 UTC, Chartman123 commented on src/components/SidebarTabs/SharingSidebarTab.vue
> +				<h2>{{ form.title }}</h2>
Yes, just include the translated word "Share" into the heading :) so `t('forms', 'Share {formTitle}', { formTitle: form.title })`

2024-05-16 13:08 UTC, Chartman123 commented on src/components/SidebarTabs/SharingSidebarTab.vue
> +			<NcActions>margin
Probably not intended ;)

2024-05-16 14:43 UTC, Himmelxd commented on src/components/SidebarTabs/SharingSidebarTab.vue
> +			},
I would do QRCodeDialog in a separate component if @Chartman123 is fine with that.

2024-05-16 14:52 UTC, Chartman123 commented on src/components/SidebarTabs/SharingSidebarTab.vue
> +			},
Yes, fine for me as well

2024-05-17 19:55 UTC, Chartman123 reviewed
Some small comments again... Please also do another rebase to squash all commits into one.

2024-05-17 19:55 UTC, Chartman123 commented on src/components/QRDialog.vue
> +				:alt="t('forms', 'QR code representation of {title}', { title: title })">
Just another quick fix: the QR code doesn't represent the form title, but the share link. So we need to use `text` here, too:
```suggestion
				:alt="t('forms', 'QR code representation of {text}', { text: text })">
```

2024-05-17 19:55 UTC, Chartman123 commented on src/components/SidebarTabs/SharingSidebarTab.vue
> +import IconQr from 'vue-material-design-icons/Qrcode.vue'
The wrong ordering came back

2024-05-17 19:55 UTC, Chartman123 commented on src/components/SidebarTabs/SharingSidebarTab.vue
> +		IconQr,
Same here again...

2024-05-21 09:19 UTC, susnux requested changes
Thank you for the changes!

But I still have some changes :see_no_evil: 
I meant to abstract the whole dialog as a component, so also move the `NcDialog` to the `QRDialog` component.

Some minor stuff like making it reactive (currently in your version the *uri* is only built on create).

2024-05-21 09:19 UTC, susnux commented on src/components/QRDialog.vue
> +	</div>
```suggestion
	<NcDialog class="qr-dialog"
		close-on-click-outside
		:name="title"
		:open="open"
		@close="$emit('close')>
		<div class="qr-dialog__content">
			<img :src="uri"
				:title="text"
				:alt="t('forms', 'QR code representation of {text}', { text: text })">
		</div>
	</NcDialog>
```

The idea is to wrap the dialog not only the content, especially to use the NcDialog `name` instead of custom heading.

2024-05-21 09:19 UTC, susnux commented on src/components/QRDialog.vue
> +	},
```suggestion
	watch {
		text: {
			immediate: true,
			handler() {
				this.generateQr()
			},
		},
	},
```

Allow to be reactive to prop changes.

2024-05-21 09:19 UTC, susnux commented on src/components/QRDialog.vue
> +}
```suggestion
.qr-dialog__content {
	display: flex;
	justify-content: space-around;
	width: 100%;
}
```

2024-05-21 09:19 UTC, susnux commented on src/components/SidebarTabs/SharingSidebarTab.vue
> +					<NcActionButton @click="openQrDialog(getPublicShareLink(share))">
```suggestion
					<NcActionButton @click="openQrDialog(share)">
```

Better to handle the logic in the method than in the template.

2024-05-21 09:19 UTC, susnux commented on src/components/SidebarTabs/SharingSidebarTab.vue
> +		</NcDialog>
```suggestion
		<QRDialog :open="qrDialogText !== null"
			:title="t('forms', 'Share {formTitle}', { formTitle: form.title })" 
			:text="qrDialogText"
			@close="qrDialogText = null" />
```

Abstract the dialog and move it to the component instead.

2024-05-21 09:19 UTC, susnux commented on src/components/SidebarTabs/SharingSidebarTab.vue
> +			qrDialog: false,
```suggestion
			qrDialogText: null,
```

Mixing boolean and string here is not really obvious I think, so instead make it string by default with `null` to explicitly mark *no value*.

2024-05-21 09:19 UTC, susnux commented on src/components/SidebarTabs/SharingSidebarTab.vue
> +		},
```suggestion
		openQrDialog(share) {
			this.qrDialogText = getPublicShareLink(share)
		},
```

see above (also this is not async)

2024-05-21 09:19 UTC, susnux commented
PS: My code suggestions are only to show what I meant, they are not tested and need some refactoring ;)

2024-06-16 22:44 UTC, Himmelxd commented on src/components/QRDialog.vue
> +	</div>
Yes, it definitely had some refactoring due, like missing quotes ;) .
Was more struggling with opening and closing and reopening of NcDialog though.

2024-06-24 12:38 UTC, Chartman123 requested changes
Copyright information is missing in QRDialog.vue

2024-07-05 22:12 UTC, Chartman123 approved these changes
Everything's fine from my side :)

@susnux can we merge this now?

2024-07-07 17:33 UTC, susnux approved these changes

2024-07-07 17:34 UTC, susnux commented
@Himmelxd Thank you very much, awesome work :rocket:  Hope to see more contributions in the future!

2024-07-07 17:34 UTC, merged