Do not submit fields that not exists anymore
nextcloud/forms pull request #2312
Opened 2024-09-07 21:20 UTC by Koc

This pr aims to fix next bug. Here an reproducer

1. Create form with 2 questions
2. Start filling the form but don't submit it
3. Edit form and remove 1st question

Expected result: form successfully submitter

Actual result: there is an error on BE side

2024-09-08 16:07 UTC, Chartman123 requested changes
Nice catch :)

However, with your changes the values for Dropdown, Date and Time questions aren't loaded anymore. Other than that some small comments/improvements to the code.

Instead of doing it when loading from LocalStorage we could also check it on submission and remove answers for invalid questions there. What do you think?

2024-09-08 19:01 UTC, susnux commented
Maybe rather show a warning like: "Warning the form has changed since you last visit, do you want to restart?"
As also already filled questions might have changed the wording or similar. But also maybe something to track in an issue

2024-09-09 23:00 UTC, Koc commented
@Chartman123 thanx for suggestion, I've changed approach

![image](https://github.com/user-attachments/assets/b092a971-5d2a-458e-8bf9-737895c20b29)

@susnux yeah, we can, but let's fix issue first. BTW what component can I use for raising this warning?

2024-09-10 06:41 UTC, Chartman123 commented
@Koc I'll have a look at it and test it this evening :)

2024-09-10 18:34 UTC, Chartman123 commented
> what component can I use for raising this warning?

You should use NcDialog like the two existing ones in Submit.vue :)

2024-09-10 18:35 UTC, Chartman123 submitted a review, later dismissed

2024-09-11 21:44 UTC, Koc commented on src/views/Submit.vue
> +			const answers = {}
Because previously `const answers = []` was defined inside `for` statement where we iterated all stored answers. But now this variable defined before iteration.

so, previously: it was `[1, 2]` but now `{33: [1, 2], 34: "text answer"}`

2024-09-11 22:36 UTC, Chartman123 approved these changes

2024-09-11 22:36 UTC, merged