Inform user if the form is anonymous
nextcloud/forms pull request #635
Opened 2020-10-12 08:06 UTC by Nienzu

Signed-off-by: nienzu <ibqqz0602@gmail.com>

2020-10-12 08:07 UTC, Nienzu commented
Implement #530

2020-10-12 08:47 UTC, skjnldsv requested changes

2020-10-12 08:47 UTC, skjnldsv commented on src/views/Create.vue
> +				<template v-if="isAnonymous">
Hey!
There is a cleaner way to do that :)
Could you create a computed like `infoMessage` that returns those strings based on the `isAnonymous`/`mandatoryUsed` directly?
That would keep the template clean :wink:

2020-10-12 10:13 UTC, Nienzu commented on src/views/Create.vue
> +				<template v-if="isAnonymous">
Thanks for the suggestion!

2020-10-12 10:15 UTC, Nienzu commented on src/views/Create.vue
> +				<template v-if="isAnonymous">
I use  v-text to keep the template clean.

2020-10-12 10:24 UTC, skjnldsv commented on src/views/Create.vue
> +			if (isMandatoryUsed) {
```suggestion
		isMandatoryUsed() {
			return this.form.questions.reduce((isUsed, question) => isUsed || question.mandatory, false)
		},
		infoMessage() {
			if (this.isMandatoryUsed) {
```

2020-10-12 10:24 UTC, skjnldsv commented on src/views/Create.vue
> +			}
You can use string combination to avoid making translators write 4 different translations :)

```suggestion
			let message = ''
			if (this.form.isAnonymous) {
				message += t('forms', 'Responses are connected to your Nextcloud account.')
			} else {
				message += t('forms', 'Responses are anonymous.')
			}
			if (this.isMandatoryUsed) {
				message += ' ' + t('forms', 'An asterisk (*) indicates mandatory questions.')
			}
			return message
```

Also, are you sure about `this.form.isAnonymous` ?
shouldn't we return `Responses are anonymous` when it's true instead? Missing a `!` ?

2020-10-12 12:38 UTC, jotoeri reviewed
Nice! 💪 
Just one small addition to previous comments. ;)

2020-10-12 12:38 UTC, jotoeri commented on src/views/Create.vue
> +			<p class="info-mandatory" v-text="infoMessage" />
Maybe rename also to info-message? Just for consistency...

2020-10-13 02:02 UTC, Nienzu commented on src/views/Create.vue
> +			}
It's my mistake. Thanks!!

2020-10-13 02:02 UTC, Nienzu commented on src/views/Create.vue
> +			<p class="info-mandatory" v-text="infoMessage" />
That sounds good. Let's do it!

2020-10-13 08:14 UTC, jotoeri approved these changes
Looks good to me 👍 🚀

2020-10-13 09:47 UTC, skjnldsv approved these changes

2020-10-13 09:48 UTC, merged

2020-10-13 09:48 UTC, skjnldsv commented
:rocket: :tada:

2020-10-13 10:30 UTC, jancborchardt commented
By the way @Nienzu we have a Nextcloud Talk instance for quicker communication among contributors, with channels for e.g. the Forms app, Deck app, Vue team etc. :) If you like we can add you there via the email from your commits?

2020-10-14 02:12 UTC, Nienzu commented
@jancborchardt 
Yes, it sounds cool~Thanks for your invitation : )