Clone Forms
nextcloud/forms pull request #756
Opened 2021-01-24 16:11 UTC by jotoeri

I was just motivated to do this, so here it is... 😉 
In fact, it is a done thing, just based upon my previous PRs, as it includes API Doc and OCS-API already. Therefore as draft for now.

![grafik](https://user-images.githubusercontent.com/47433654/105635800-41962980-5e65-11eb-81ae-b66980799e3a.png)

2021-02-10 14:50 UTC, jancborchardt commented
Very nice! First design feedback would be to adjust the wording to the less technical "Copy form". Yes, "Copy share link" should then be changed to "Share link" :)

Reason for the change is that "Copy form" or "Duplicate form" are much more common words than "Clone", and copy is exactly what is done, like cut/copy/paste. :)

2021-02-17 11:14 UTC, skjnldsv requested changes

2021-02-17 11:14 UTC, skjnldsv commented on src/components/AppNavigationForm.vue
> +
Please do the cloning here. Same as the delete. No need to forward it to the parent :)

2021-02-17 15:05 UTC, jotoeri commented on src/components/AppNavigationForm.vue
> +
Hm, i just pushed a fixup, but i'm not convinced of this. We have to insert the new Form on parent into the list, so now we have some operation in two places. If we just do everything on parent, then it's all in one place. And it seems more logical to me, if new Forms are handled on the list, instead of a form handling another form...?
So if you're ok with, i'd rather delete the fixup again... 🙈

2021-02-17 15:25 UTC, jotoeri commented
So - Wording is adapted, also adapted it on all occurences of the Share Link. Therefore, on the empty-content i included the Clippy-icon, so the button is not lost with the short text... @jancborchardt Is that good like this?
![grafik](https://user-images.githubusercontent.com/47433654/108223489-2b188080-713a-11eb-9893-5673b1e823ab.png)
![grafik](https://user-images.githubusercontent.com/47433654/108223594-44b9c800-713a-11eb-9a92-5b1c3ea0dba2.png)
![grafik](https://user-images.githubusercontent.com/47433654/108225683-7338a280-713c-11eb-9f7d-7136f1874f20.png)

2021-02-17 16:29 UTC, skjnldsv commented on src/components/AppNavigationForm.vue
> +
Ah, I get the point.
Yeah, fair enough! :)

2021-02-18 07:40 UTC, skjnldsv approved these changes

2021-02-22 08:44 UTC, skjnldsv commented
We should really have unit tests for those stuff.

2021-02-22 08:44 UTC, merged