Show shared forms on navigation
nextcloud/forms pull request #763
Opened 2021-02-01 00:12 UTC by jotoeri

Show the shared forms on navigation. Implements #364

- API Docs are still missing.

2021-02-10 19:00 UTC, jotoeri commented
Hm, @jancborchardt are you sure, you want it to have like this? I could imagine this becomes a bit confusing if the list becomes longer. Especially if we somewhen add further lists like for Result-Sharing or a collapsed one for kind of an archive?
The old way it was collapsable from the vue-components. Wouldn't it be better if we just use the component and probably reduce the inset/change the style there a bit (effecting of course all using apps)?
![grafik](https://user-images.githubusercontent.com/47433654/107555293-484bcd00-6bd7-11eb-80e3-730056976679.png)

2021-02-10 20:38 UTC, jotoeri commented
And for reference the same vue-components change (half inset) also on deck and polls. 😉 I really like it like this!
![grafik](https://user-images.githubusercontent.com/47433654/107568787-c7490180-6be7-11eb-9da7-b92b0ad950c4.png)
![grafik](https://user-images.githubusercontent.com/47433654/107566185-dbd7ca80-6be4-11eb-9027-c943b2ac722f.png)
![grafik](https://user-images.githubusercontent.com/47433654/107569114-3888b480-6be8-11eb-9959-c13d27a40816.png)

2021-02-17 11:12 UTC, skjnldsv commented
Should probably be "My forms" instead. cc @jancborchardt

2021-02-17 16:16 UTC, jotoeri commented
> 
> 
> Should probably be "My forms" instead. cc @jancborchardt

Yeah, if you have a look onto the first two pictures, this is already 'Your Forms' and 'Shared with you'.

I think the most important question is for now: How do we list the forms on navigation? @jancborchardt @skjnldsv 
- Collapsable Navigation Item? Maybe with a decreased inset, as on the last picture of my previous comment? @skjnldsv Do you think we would get that through on vue-components? (This is my favourite)
- Non-Collapsable just listed with AppNavigationCaption (w/o icon) or with AppNavigationItem (w/ icon)

2021-02-22 13:15 UTC, jancborchardt commented
I think this one you posted looks most proper @jotoeri? It’s similar to the Settings with "Personal" and "Admin" headings in the nav, isn’t that in the components as well? Cause the headings themselves actually do not need to be _selectable_ entries, just separators.

> ![image](https://user-images.githubusercontent.com/925062/108713255-40b1ef80-7518-11eb-8ca0-426e1ec89e84.png)

2021-02-22 14:34 UTC, jotoeri commented
Yes, it's also a component. I would have liked more the collapsable solution. But ok. Now its the Caption-Version.

![grafik](https://user-images.githubusercontent.com/47433654/108722250-377a5000-7523-11eb-9007-4558cae237f1.png)
![grafik](https://user-images.githubusercontent.com/47433654/108722164-203b6280-7523-11eb-824f-8296c5aba384.png)

2021-02-23 12:54 UTC, skjnldsv commented
If "your forms" is empty, we should not display an empty list, I think we should add a small message?

2021-02-23 14:21 UTC, jotoeri commented
Yeah, had that also in mind... But would need probably some AppNavigationEmptyContent on components?! Seems like the AppNavigation only takes appropriate components inside the template, no?

2021-02-23 14:53 UTC, skjnldsv commented
> But would need probably some AppNavigationEmptyContent on components?!

I don't think we'd have too much usage for it. Maybe just remove the title and spacing? Just show th shared ones?

The main content should already state that you don't have any and you can create new ones, no?

2021-02-23 15:03 UTC, jotoeri commented
Yeah, you're right. The Spacer i just removed completely as i realised, the Caption does that itself. So no need to have twice a space.
![grafik](https://user-images.githubusercontent.com/47433654/108862465-8d68f980-75f0-11eb-9e6b-ae85e054c04c.png)
![grafik](https://user-images.githubusercontent.com/47433654/108862548-a1146000-75f0-11eb-985f-a97102043f4c.png)

2021-02-23 15:32 UTC, skjnldsv commented on appinfo/routes.php
> +		['name' => 'page#index', 'url' => '/{hash}/{action}', 'verb' => 'GET', 'defaults' => ['hash' => '', 'action' => '']],
nice!

2021-02-23 15:33 UTC, skjnldsv commented on src/Forms.vue
> +			this.forms.owned.splice(formIndex, 1)
I think I would have been more confident having two separate array for this, `forms` and `sharedForms`

2021-02-23 15:34 UTC, skjnldsv requested changes

2021-02-23 15:34 UTC, skjnldsv commented on src/Forms.vue
> +			},
I think I would have been more confident having two separate array for this, `forms` and `sharedForms`

I'm really not fond of nested values in data.

2021-02-23 17:03 UTC, jotoeri commented on src/Forms.vue
> +			},
🤷‍♂️ Changed that...

2021-02-24 01:07 UTC, jotoeri commented
Just thougth about the access stuff again, to fix the redirect-thing #539. As it also clarifies/secures the work & code here, i squashed it in here, instead of a separate PR, that would change the changes of this PR afterwards.
Sorry for this change after the first review. The result here just seems to be more clear & clean to me. 🙈

2021-02-24 08:08 UTC, skjnldsv commented on src/Forms.vue
> +					@mobile-close-navigation="mobileCloseNavigation" />
Maybe also hide if there is no "shared forms" ?

2021-02-24 09:45 UTC, jotoeri commented on src/Forms.vue
> +					@mobile-close-navigation="mobileCloseNavigation" />
👍

2021-02-24 23:10 UTC, jotoeri commented
Just added and already squashed one more small fix, that i just found: https://github.com/nextcloud/forms/pull/763/commits/171d43b08f5bc88d891c135358a85cd27eef64bd

2021-02-25 14:31 UTC, jotoeri commented on src/Forms.vue
> +			}
Opened an issue to keep track:  #806

2021-02-25 14:32 UTC, jotoeri commented on src/Forms.vue
> +			return this.forms && (this.forms.length === 0)
First line here would not work i think, but included the rest: https://github.com/nextcloud/forms/pull/763/commits/e8ec9dc5c8a34c07a66627c3dc117fa272db3b0a

2021-02-25 15:01 UTC, jotoeri commented on src/Forms.vue
> +				const response = await axios.get(generateOcsUrl('apps/forms/api/v1', 2) + 'forms/shared')
Yeah, i remember struggling on this, too. I changed it. 👍

2021-02-26 08:02 UTC, skjnldsv commented on src/Forms.vue
> +			return this.noOwnedForms && this.noSharedForms
Ah right, double negative! :grin:

2021-02-26 08:04 UTC, skjnldsv approved these changes
Good for me! Please rebase :rocket:

2021-02-26 08:04 UTC, skjnldsv commented
Ah, sorry, I thought I saw a fixup! ALl good then! :shipit:

2021-02-26 08:04 UTC, merged

2021-03-11 17:05 UTC, jotoeri commented on appinfo/routes.php
> +		['name' => 'page#index', 'url' => '/{hash}/{action}', 'verb' => 'GET', 'defaults' => ['hash' => '', 'action' => '']],
@rullzer, @nickvergessen, @ChristophWurst does one of you know about any problems with such generic route?
We have a few users now reporting they can not open the App via Navigation. But seems a bit specific to nginx-users 🤔

Should we eventually re-include the line without any parameters again?

2021-03-24 09:27 UTC, nickvergessen commented on appinfo/routes.php
> +		['name' => 'page#index', 'url' => '/{hash}/{action}', 'verb' => 'GET', 'defaults' => ['hash' => '', 'action' => '']],
well I guess the route `index.php/apps/forms//` might not evaluate the same with all webservers and therefor result in problems later. I would suggest to just add multiple routes instead.