Disable iPhone Auto-Zoom
nextcloud/forms pull request #816
Opened 2021-03-01 11:36 UTC by jotoeri

Including a small script to disable the auto-zooming on iphones.
- I tested it on Firefox and Edge NC20 & NC21, where zooming still works.
- I also tested on Android Firefox and LineageOS Stock-Browser, where Zooming still works more or less. Means: Just as bad as before, so this PR does not change the zooming there. (One can zoom on the sidebar and navigation, but not on the main content. Seems to me like some vue-css/config issue...)
- The idea is from https://stackoverflow.com/a/57527009/14998011 and https://stackoverflow.com/a/9039885/14998011

@idecable, @kacenka49, @auviolon, @jordan-richardo Could some of you check, if this works on different iOS devices? Ideally also, if zooming still works on some Mac Desktop devices?

Should fix #523

2021-03-01 13:51 UTC, skjnldsv requested changes
Oh no, this should most likely be done with php. :see_no_evil: 
This seems like a terrible hack to have :grin:

2021-03-01 20:00 UTC, idecable commented
> Oh no, this should most likely be done with php. 🙈
> This seems like a terrible hack to have 😁

 Can you elaborate more? This is a client side detail, not a backend problem. I don't know everything by far, always learning something new, but I have experimented. 

<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=0"> adding this worked for me in the template. Have not tested on Android, but will certainly try this week.

Many talked options: changing the size of the input text fields, so that it would prevent zoom, others mentioned adding some script that would ensure the page will zoom-out when you leave the text input fields.. I'm open to all approaches, as long it does the job. I was up to a point where I wanted to attempt moving the Submit button to the left side as opposed to the right side. So many different ways. 

But yes by all means, let the best tweak win. 😁

2021-03-01 23:54 UTC, idecable commented
Wow the PageController edit is very well done. Now I want to learn more PHP

2021-03-02 00:01 UTC, jotoeri commented
Hmm, indeed, this works quite easy on php...^^
- I'm not sure, if the Regex is ideal. Maybe somebody with a bit more of Regex-Experience could double-check that. I checked it with several strings, it seems to work so far... 🤔 https://regex101.com/r/wepuAT/1 with strings from: [beamtic.com unknown?](https://beamtic.com/user-agents/?browser=Safari) and with [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent#safari_ua_string)
- The viewport string is the one, that comes already with NC, just extended with the `maximum-scale`-term.

2021-03-02 00:02 UTC, jotoeri commented
@idecable did you check already on iOS if this works? 👀

2021-03-02 00:09 UTC, idecable commented
> @idecable did you check already on iOS if this works? 👀

I didn't apply your fix to my setup yet, but I like how you structured this up. 

I could create an instance with your added code in a few days, and test on Android emulator as well.

2021-03-02 00:16 UTC, jotoeri commented
> I could create an instance with your added code in a few days, and test on Android emulator as well.

That would be nice 😊 💪

2021-03-02 06:31 UTC, skjnldsv commented
> * I'm not sure, if the Regex is ideal. Maybe somebody with a bit more of Regex-Experience could double-check that. I checked it with several strings, it seems to work so far... thinking [regex101.com/r/wepuAT/1](https://regex101.com/r/wepuAT/1) with strings from: [beamtic.com unknown?](https://beamtic.com/user-agents/?browser=Safari) and with [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent#safari_ua_string)

We have existing user agents constants if you want :)
https://github.com/nextcloud/server/blob/eb502c02ff7693bb36318d857985f79e7bac370c/lib/private/AppFramework/Http/Request.php#L67-L79

2021-03-02 09:51 UTC, jotoeri commented
> We have existing user agents constants if you want

Ahh, that's good, yes 👍. However the safari-constant does not match for iPhones, as the Mobile-Part is missing. I used now the syntax from the constant, but included the `iPhone` and the `Mobile`-Part.

2021-03-02 20:48 UTC, skjnldsv approved these changes

2021-03-08 13:00 UTC, jotoeri commented
Ok, so i meanwhile created a testinstance:
@idecable, @kacenka49, @auviolon, @jordan-richardo, would be cool, if some of you could check on these two forms, if the fix works:
- First one is on master branch, which should still contain the bug (for reference): http://h2643730.stratoserver.net/testcloud/index.php/apps/forms/je6MH2PEcpzP8CBS
- Second one is on this bugfix-branch, which hopefully does not show the bug anymore: http://h2643730.stratoserver.net/testcloud2/index.php/apps/forms/oqTwPeCk3xaYoS6a

2021-03-08 23:40 UTC, jotoeri commented
Ok, got one confirmation on the forum, another one by a friend of mine. This works, so let's go here. 👍 🙂

2021-03-08 23:43 UTC, merged

2021-03-09 01:41 UTC, idecable commented
> Ok, so i meanwhile created a testinstance:
> @idecable, @kacenka49, @auviolon, @jordan-richardo, would be cool, if some of you could check these two forms on your iPhone, for if the fix works:
> 
> * First one is on master branch, which should still contain the bug (for reference): http://h2643730.stratoserver.net/testcloud/index.php/apps/forms/je6MH2PEcpzP8CBS
> * Second one is on this bugfix-branch, which hopefully does not show the bug anymore: http://h2643730.stratoserver.net/testcloud2/index.php/apps/forms/oqTwPeCk3xaYoS6a

> 

Are these links offline? Unable to load both.

2021-03-09 09:12 UTC, jotoeri commented
Ah, yes sorry, so i was just two hours too fast. The server got deleted, as it was an old one, which i could just quickly use for a public link, before it will die. 🙈 
But it's merged now, just wait two days and you'll have it on your own instance through the app-store. 😉 🚀