Fix codecov token
nextcloud/forms pull request #821
Opened 2021-03-04 09:06 UTC by skjnldsv

2021-03-05 10:29 UTC, ChristophWurst approved these changes

2021-03-28 21:08 UTC, jotoeri commented
How about this one, @skjnldsv? This should make codecov reacting a bit more reliably, no?
Seems to me from the log, as it would only be to increase the fetch-depth to make it run? 🤔

2021-03-28 21:09 UTC, jotoeri commented on phpunit.xml
> +		<directory>./tests/unit</directory>
Uppercase `Unit` here for our case...?

2021-03-29 06:45 UTC, skjnldsv commented
> How about this one, @skjnldsv? This should make codecov reacting a bit more reliably, no?

I didn't found the time to finish this, feel free to take over @jotoeri :)

2021-03-29 06:47 UTC, skjnldsv commented
Rebased

2021-03-29 07:37 UTC, skjnldsv commented
@jotoeri
`fixup! DO NOT MERGE Just a test` You can review and block a pr ;)

2021-03-29 07:55 UTC, jotoeri requested changes
Well then... 😉

2021-03-29 10:34 UTC, skjnldsv commented on composer.json
> +		"test:integration": "phpunit -c tests/phpunit.integration.xml"
Much cleaner! :heart_eyes:

2021-03-29 11:04 UTC, jotoeri commented
Huhh - that was a hard one. 😅 
But seems to work now.
- I further moved the phpunit-stuff into the tests-dir. Probably one could move the codecov.yml too somewhen, but the codecov-action seems not to get that resolved currently.
- Codecov-comments should now only happpen if relevant and be a bit shorter

I'd probably wait with the merge until https://codecov.io/gh/nextcloud/forms/commit/047bee0a81a4e5f806e583481897143f6a4f0281 is done, but i assume that should be good.

2021-03-29 11:06 UTC, jotoeri approved these changes
🙈

2021-03-29 11:17 UTC, merged