Delete a deleted Users Forms
nextcloud/forms pull request #856
Opened 2021-03-15 20:06 UTC by jotoeri

As we talked about, i was interested to do this. 😄 And it was just too easy to implement. 🙈 
Basically a done PR here, i'd just still wait for a while until we don't see urgent bugs for v2.2.2 anymore. 😉 

Implements #828

2021-03-16 07:12 UTC, skjnldsv commented
Is this ready for reviews?

2021-03-16 10:52 UTC, jotoeri commented
It is, yes.
I just didn't want to merge until we know, we don't need a `v2.2.3`. And i didn't know how to mark that ideally.^^

2021-03-16 14:13 UTC, skjnldsv commented on lib/Db/FormMapper.php
> +		$this->delete($form);
Could there be an error here? If so do we need to catch and log?
Maybe also just log debug by default as well?

2021-03-16 16:16 UTC, jotoeri commented on lib/Db/FormMapper.php
> +		$this->delete($form);
Logging is done one level higher on API and BackgroundJob respectively.
Regarding errors, this should be ok, as we only delete, what we first got from db. So as long as there is no kind of 'read-only'-Db that should work. 😉

2021-03-16 16:21 UTC, skjnldsv approved these changes

2021-03-25 11:28 UTC, skjnldsv commented
Rebase and squash?

2021-03-26 08:13 UTC, skjnldsv approved these changes

2021-03-26 08:13 UTC, skjnldsv commented
php cs lint fails

2021-03-26 08:21 UTC, jotoeri commented
That's the php-cs-fixer bug... So wie can either ignore it for now, or i'll rebase on the weekend onto #864 😉

2021-03-27 22:08 UTC, jotoeri commented
Rebase is done meanwhile, but please don't merge, until #871 is merged and released. 😞

2021-03-28 17:38 UTC, skjnldsv requested changes
Blocking then

2021-04-01 11:28 UTC, rullzer commented
So good to go now?

2021-04-01 11:57 UTC, jotoeri commented
Yeah, should be good... 👍  I just hope we don't need a 2.2.5 🙈

2021-04-01 12:01 UTC, skjnldsv approved these changes

2021-04-14 12:14 UTC, jotoeri commented
Just rebased, so i'd say lets go here. 😉

2021-04-14 14:22 UTC, merged